### ISSUE TITLE
Recent update ends quietly, Kalabox can't start servers, and re-start installation after reopening

### ISSUE THREAD

**Issue by kopeboy** [kalamuna/kalaboxv1#103]
I was noticed of an update. I click to proceed with it. Went on doing something else afk, I come back and I see nothing other than normal Kalabox window with Stopped servers. If I try to start them it shows an error and can't start. I quit Kalabox. On reopening big green button of "Box me" appears, like a first installation, and after a few seconds I get Uh Oh unexpected error.
This is the log: 
### Kalabox Log

2014-07-11T21:08:19.374Z - info: Box initialized.
2014-07-11T21:08:19.376Z - info: Kalabox Version: 1.0-beta6
2014-07-11T21:08:19.381Z - info: Mac OS Version: 10.9.4

2014-07-11T21:08:19.381Z - info: VirtualBox Version: false
2014-07-11T21:08:19.381Z - info: Vagrant Version: false
2014-07-11T21:27:34.499Z - info: VirtualBox not installed or wrong version. Installing.
2014-07-11T21:27:34.500Z - info: User granted permission to install VirtualBox
2014-07-11T21:41:42.408Z - info: Successfully downloaded VirtualBox DMG.
2014-07-11T21:41:59.075Z - info: Successfully mounted VirtualBox DMG.
2014-07-11T21:42:20.758Z - info: VirtualBox installation complete.
2014-07-11T21:42:21.028Z - info: Successfully ejected VirtualBox DMG.
2014-07-11T21:42:21.029Z - info: Vagrant not installed or wrong version. Installing.
2014-07-11T21:42:21.029Z - info: User granted permission to install Vagrant
2014-07-11T21:46:50.104Z - info: Successfully downloaded Vagrant DMG.
2014-07-11T21:46:53.105Z - info: Successfully mounted Vagrant DMG.
2014-07-11T21:47:00.096Z - info: Vagrant installation complete.
2014-07-11T21:47:00.202Z - info: Successfully ejected Vagrant DMG.
2014-07-11T22:12:59.205Z - info: Box image downloaded.
2014-07-11T22:13:00.928Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-07-11T22:13:01.999Z - info: Kalastack downloaded
2014-07-11T22:13:02.000Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-07-11T22:13:19.274Z - info: Adding base box image to Vagrant.
2014-07-11T22:13:20.999Z - info: Wrote configuration file.
2014-07-11T22:13:21.041Z - info: Executing box spinup.
2014-07-11T22:13:21.073Z - info: Starting spinup attempt 0
2014-07-11T22:24:54.463Z - info: Box initialized.
2014-07-11T22:24:54.464Z - info: Kalabox Version: 1.0-beta6
2014-07-11T22:24:54.465Z - info: Mac OS Version: 10.9.4

2014-07-11T22:24:54.465Z - info: VirtualBox Version: 4.3.6r91406

2014-07-11T22:24:54.465Z - info: Vagrant Version: Vagrant 1.4.3

2014-07-11T22:24:54.466Z - info: Installation completed successfully.
2014-07-11T22:24:54.808Z - info: Existing VirtualBox installation, version 4.3.6
2014-07-11T22:24:54.810Z - info: Existing Vagrant installation, version 1.4.3
2014-07-11T22:24:54.819Z - info: Kalabox image already downloaded.
2014-07-11T22:24:54.819Z - info: Box image downloaded.
2014-07-11T22:24:54.821Z - info: Kalastack already downloaded
2014-07-11T22:24:54.821Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-07-11T22:24:55.541Z - info: Kalastack downloaded
2014-07-11T22:24:55.543Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-07-11T22:25:12.321Z - info: Wrote configuration file.
2014-07-11T22:25:12.352Z - info: Executing box spinup.
2014-07-11T22:25:12.382Z - info: Starting spinup attempt 0
2014-07-11T22:25:14.251Z - info: Box initialized.
2014-07-11T22:25:14.252Z - info: Kalabox Version: 1.0-beta6
2014-07-11T22:25:14.252Z - info: Mac OS Version: 10.9.4

2014-07-11T22:25:14.252Z - info: VirtualBox Version: 4.3.6r91406

2014-07-11T22:25:14.252Z - info: Vagrant Version: Vagrant 1.4.3

2014-07-11T22:25:14.252Z - info: Installation completed successfully.
2014-07-11T22:34:08.890Z - warn: An error occurred in an async call.
cause stack is ...
  Error: Command failed: Authentication failed. Please check your credentials and try again.      [error]

```
at ChildProcess.exithandler (child_process.js:661:12)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Socket.eval (child_process.js:994:11)
at Socket.EventEmitter.emit (events.js:98:17)
at Pipe.eval [as close] (net.js:459:12)
```

async call history is ...
 [ { function: 'authenticate2',
    location: '/private/var/folders/5p/jvfmmj4522718fv5jkbpck0w0000gn/T/.org.chromium.Chromium.AAZBVu/kalabox/utils/pantheon-auth.js:93:76',
    mapping: { description: 'tail' } } ]
2014-07-12T12:49:34.113Z - info: Box initialized.
2014-07-12T12:49:34.114Z - info: Kalabox Version: 1.0-beta6
2014-07-12T12:49:34.114Z - info: Mac OS Version: 10.9.4

2014-07-12T12:49:34.114Z - info: VirtualBox Version: 4.3.6r91406

2014-07-12T12:49:34.114Z - info: Vagrant Version: Vagrant 1.4.3

2014-07-20T11:14:25.556Z - info: Box initialized.
2014-07-20T11:14:25.557Z - info: Kalabox Version: 1.0-beta6
2014-07-20T11:14:25.557Z - info: Mac OS Version: 10.9.4

2014-07-20T11:14:25.557Z - info: VirtualBox Version: 4.3.6r91406

2014-07-20T11:14:25.557Z - info: Vagrant Version: Vagrant 1.4.3

2014-07-29T17:53:25.574Z - info: Box initialized.
2014-07-29T17:53:25.576Z - info: Kalabox Version: 1.0-beta6
2014-07-29T17:53:25.576Z - info: Mac OS Version: 10.9.4

2014-07-29T17:53:25.576Z - info: VirtualBox Version: 4.3.6r91406

2014-07-29T17:53:25.576Z - info: Vagrant Version: Vagrant 1.4.3

2014-07-29T18:27:30.426Z - warn: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-07-29T18:27:30.538Z - warn: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-07-29T18:27:54.556Z - info: Box initialized.
2014-07-29T18:27:54.557Z - info: Kalabox Version: 1.0-beta6
2014-07-29T18:27:54.557Z - info: Mac OS Version: 10.9.4

2014-07-29T18:27:54.558Z - info: VirtualBox Version: 4.3.6r91406

2014-07-29T18:27:54.558Z - info: Vagrant Version: Vagrant 1.4.3

2014-07-29T18:28:07.061Z - info: Existing VirtualBox installation, version 4.3.6
2014-07-29T18:28:07.061Z - info: Existing Vagrant installation, version 1.4.3
2014-07-29T18:28:07.068Z - info: Kalabox image already downloaded.
2014-07-29T18:28:07.069Z - info: Box image downloaded.
2014-07-29T18:28:07.071Z - info: Kalastack already downloaded
2014-07-29T18:28:07.071Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-07-29T18:28:07.727Z - info: Kalastack downloaded
2014-07-29T18:28:07.728Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-07-29T18:28:22.883Z - info: Wrote configuration file.
2014-07-29T18:28:22.915Z - info: Executing box spinup.
2014-07-29T18:28:22.949Z - info: Starting spinup attempt 0
2014-07-29T18:28:23.418Z - warn: Spinup attempt 0 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-07-29T18:28:23.936Z - info: Starting spinup attempt 1
2014-07-29T18:28:24.411Z - warn: Spinup attempt 1 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-07-29T18:28:24.901Z - info: Starting spinup attempt 2
2014-07-29T18:28:25.370Z - warn: Spinup attempt 2 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-07-29T18:28:25.822Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Failed to spin up virtual machine after 3 attempts. Error was: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

```
at eval (/private/var/folders/5p/jvfmmj4522718fv5jkbpck0w0000gn/T/.org.chromium.Chromium.8HNIBx/kalabox/installer/install-utils.js:359:22)
at ChildProcess.exithandler (child_process.js:665:7)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Socket.eval (child_process.js:994:11)
at Socket.EventEmitter.emit (events.js:98:17)
at Pipe.eval [as close] (net.js:459:12)
```

async call history is ...
 [ { function: 'install16',
    location: '/private/var/folders/5p/jvfmmj4522718fv5jkbpck0w0000gn/T/.org.chromium.Chromium.8HNIBx/kalabox/installer/installer.js:479:33',
    mapping: { description: 'tail' } } ]
##

**Comment by pirog** [comment]
Shit.

Can you tell me what you have in ~/.kalabox/kalastack?

**Comment by kopeboy** [comment]
Only config.json:

{
  "boxname": "kalabox",
  "boxuser": "vagrant",
  "kalastack_version": "3.0-beta4",
  "terminatur_version": "1.0-beta1",
  "puppet_environment": "threebetathree",
  "default_memory": "2048",
  "memory_divisor": "4",
  "box_location": {
    "32": "http://files.kalamuna.com/kalabox32.box",
    "64": "http://files.kalamuna.com/kalabox64.box"
  },
  "ip": "1.3.3.7",
  "host_ip": "1.3.3.1",
  "host_entries": [
    "kala",
    "start.kala",
    "php.kala",
    "grind.kala",

**Comment by pirog** [comment]
well, that will definitely do it. strange its not grabbing the new stack. 

try extracting the lastest kalastack release into that directory 
https://github.com/kalamuna/kalastack/releases/tag/3.0-beta5
and be careful not to delete the hidden .vagrant and .kalabox directories. 

then try restarting Kalabox

**Comment by pirog** [comment]
@reynoldsalec if you have time to look at this real quick that would be awesome. possibly the same issue as the last update rage?

**Comment by pirog** [comment]
Anyone else who is on this issue, can you all also verify that the only thing you have in ~/.kalabox/kalastack is the config.json file?

**Comment by pirog** [comment]
I can replicate this issue and have a workaround until it is fixed. Standby.

**Comment by reynoldsalec** [comment]
Deployed the fix for this that I mentioned to you @pirog; just updated my Kalabox and everything was gravy, so I think that should mean we're good for everyone performing new updates.

**Comment by pirog** [comment]
Sweet! What was the cause of the rage?

On Tuesday, July 29, 2014, reynoldsalec notifications@github.com wrote:

> Deployed the fix for this that I mentioned to you @pirog
> https://github.com/pirog; just updated my Kalabox and everything was
> gravy, so I think that should mean we're good for everyone performing new
> updates.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/103#issuecomment-50539242.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by kopeboy** [comment]
I extracted it and opening brings up the "Oh Hello." with the big green "Box me" button.
Should I proceed?

**Comment by pirog** [comment]
No! I'll post the workaround for people who have already tried and failed
pre @reynolds update in just a second.

At the airport but will be around in 15-30.

On Tuesday, July 29, 2014, Lorenzo Giovenali notifications@github.com
wrote:

> I extracted it and opening brings up the "Oh Hello." with the big green
> "Box me" button.
> Should I proceed?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/103#issuecomment-50539668.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by kopeboy** [comment]
Nothing. Same error after clicking Box me. At ~/.kalabox/kalastack I have the hidden .vagrant and .kalabox directories and the config.json now looks like this:

{
  "boxname": "kalabox",
  "boxuser": "vagrant",
  "kalastack_version": "3.0-beta4",
  "terminatur_version": "1.0-beta1",
  "puppet_environment": "threebetathree",
  "default_memory": "2048",
  "memory_divisor": "4",
  "box_location": {
    "32": "http://files.kalamuna.com/kalabox32.box",
    "64": "http://files.kalamuna.com/kalabox64.box"
  },
  "ip": "1.3.3.7",
  "host_ip": "1.3.3.1",
  "host_entries": [
    "kala",
    "start.kala",
    "php.kala",
    "grind.kala",
    "solr.kala",
    "aliases.kala",
    "info.kala",
    "images.kala"
  ],
  "synced_www_folder": {
    "host_path": "/kalabox/www/",
    "guest_path": "/var/www/",
    "nfs": "true",
    "nfs_version": "3",
    "create": "true"
  },
  "ssh_forwarding": "false",
  "puppet_master": {
    "server": "kalabox.kalamuna.com"
  }
}

**Comment by kopeboy** [comment]
Oh sorry, I didn't refresh the page :/ thanks

**Comment by pirog** [comment]
OK. For people that tried to update and failed i think the following codescience should get you back in business.

Open up Terminal a
1. Get your VBOX Hash by running

```
$ VBoxManage list vms
```

Copy the hash, it should be in between the {}. 

In this example: 

```
"kala.fc2df93026c720aa9dc9febedcd16ea8.box" {2e5dc1a2-fe8b-4b3d-96c5-f9f7ad63844e}
```

It is 2e5dc1a2-fe8b-4b3d-96c5-f9f7ad63844e
1. Open up the VirtualBox app and make sure the box that is listed as something like kala.fc2df93026c720aa9dc9febedcd16ea8.box is powered off. If not do a normal shutdown. You may have random "Precise943g34hg" boxes showing up. If you don't know what these are you can _probably_ delete them.
2. Repair the Vagrant box ID by running

```
$ echo -n "HASHFROMABOVE" > ~/.kalabox/kalastack/.vagrant/machines/default/virtualbox/id
```
1. Download and extract the contents of the new Kalastack (https://github.com/kalamuna/kalastack/archive/3.0-beta5.tar.gz) to ~/.kalabox/kalastack. Make sure you don't delete the hidden .vagrant or .kalabox directories. To get this to open in Finder for easy drag and drop run `open ~/.kalabox/kalastack`
2. Provision your new changes by running

```
$ cd ~/.kalabox/kalastack
$ vagrant up --provision
```
1. Close VirtualBox and relaunch the Kalabox app. Turn it off and on just for good measure. This should do it.

**Comment by kopeboy** [comment]
Followed the steps.
After typing vagrant up --provision:
"A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again."

If I run "vagrant init" I get this error: 
"vm:
- The box 'base' could not be found."

Just a notice, should step 2) produce any visible output in terminal? Cause it didn't.

**Comment by kopeboy** [comment]
Ok, the problem was me extracting inside kalabox/kalastack (thus having kalabox/kalastack/kalastack-beta..) instead of inside kalabox and renaming/replacing the kalastack-beta-5 folder to kalastack.

Now "vagrant up --provision" run for a minute and Kalabox app is working.
Thank you for your fast replies and excuse my ignorance.

**Comment by pirog** [comment]
Uninstall/Reinstall is always pretty sure fire. 

If you want to continue the update ... can you verify what you have in ~/.kalabox/kalastack? maybe ... 

YUP! you beat me to it!

**Comment by pirog** [comment]
I think this pretty much resolves the issue both for new updaters and also old ones. Going to leave open for people to find but will close in a bit.
