### ISSUE TITLE
Kalabox cannot remove site after update

### ISSUE THREAD

**Issue by aristomenis** [kalamuna/kalaboxv1#108]
Hello,

Ran the update today via the Kalabox GUI "Updates Available".

Tried to remove a site via the GUI under "My Sites", and the "Error" dialog pops up with the detail message "Command cancelled".

Tried exiting and restarting Kalabox, but same result.

Any advice?

Thanks!
##

**Comment by aristomenis** [comment]
Was able to successfully remove via CLI with drush crush.

**Comment by reynoldsalec** [comment]
Wasn't able to replicate this on my own (updated) box @aristomenis, perhaps you could paste a copy of your kalabox.log (~/.kalabox/kalabox.log) and we can see what may have occurred?

**Comment by aristomenis** [comment]
Ah, good poing.  That would help, ei?  Log entry:

2014-08-01T18:01:53.744Z - warn: An error occurred in an async call.
Error message: Command failed: Command cancelled.                                                       [error]

cause stack is ...
  Error: Command failed: Command cancelled.                                                       [error]

```
at ChildProcess.exithandler (child_process.js:536:15)
at ChildProcess.EventEmitter.emit (events.js:91:17)
at maybeClose (child_process.js:634:16)
at Socket.ChildProcess.spawn.stdin (child_process.js:806:11)
at Socket.EventEmitter.emit (events.js:88:17)
at Socket._destroy.destroyed (net.js:356:10)
at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

async call history is ...
 [ { function: 't',
    location: '/Applications/Kalabox.app/Contents/Resources/kalabox/vm/sites-manager.js:6:2380',
    mapping: { description: 'tail' } } ]
2014-08-01T18:02:12.717Z - warn: An error occurred in an async call.
Error message: Command failed: Command cancelled.                                                       [error]

**Comment by pirog** [comment]
"Command cancelled" is not particularly helpful... is it? :)

The "delete" function on the UI just runs `drush crush` at the end of the day so the discrepancy is weird. 

Sometimes the delete function gets stuck with a file permission error when trying to delete settings.php but that would show up on manually running `drush crush` i think.
