### ISSUE TITLE
Error during closing — pasting the error message

### ISSUE THREAD

**Issue by oliviercp** [kalamuna/kalaboxv1#109]
### Kalabox Log

2014-08-02T00:44:09.626Z - info: Box initialized.
2014-08-02T00:44:09.626Z - info: Kalabox Version: 1.0-beta7
2014-08-02T00:44:09.627Z - info: Mac OS Version: 10.9.4

2014-08-02T00:44:09.627Z - info: VirtualBox Version: false
2014-08-02T00:44:09.627Z - info: Vagrant Version: false
2014-08-02T00:44:27.260Z - info: VirtualBox not installed or wrong version. Installing.
2014-08-02T00:44:27.261Z - info: User granted permission to install VirtualBox
2014-08-02T00:45:16.785Z - info: Successfully downloaded VirtualBox DMG.
2014-08-02T00:45:27.135Z - info: Successfully mounted VirtualBox DMG.
2014-08-02T00:45:39.840Z - info: VirtualBox installation complete.
2014-08-02T00:45:39.917Z - info: Successfully ejected VirtualBox DMG.
2014-08-02T00:45:39.917Z - info: Vagrant not installed or wrong version. Installing.
2014-08-02T00:45:39.917Z - info: User granted permission to install Vagrant
2014-08-02T00:45:45.873Z - info: Successfully downloaded Vagrant DMG.
2014-08-02T00:45:51.060Z - info: Successfully mounted Vagrant DMG.
2014-08-02T00:45:55.524Z - info: Vagrant installation complete.
2014-08-02T00:45:55.579Z - info: Successfully ejected Vagrant DMG.
2014-08-02T00:47:36.760Z - info: Box image downloaded.
2014-08-02T00:47:37.069Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-08-02T00:47:37.673Z - info: Kalastack downloaded
2014-08-02T00:47:37.673Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-08-02T00:47:43.351Z - info: Adding base box image to Vagrant.
2014-08-02T00:47:44.875Z - info: Wrote configuration file.
2014-08-02T00:47:44.906Z - info: Executing box spinup.
2014-08-02T00:47:44.946Z - info: Starting spinup attempt 0
2014-08-02T00:51:00.384Z - info: Box initialized.
2014-08-02T00:51:00.385Z - info: Kalabox Version: 1.0-beta7
2014-08-02T00:51:00.385Z - info: Mac OS Version: 10.9.4

2014-08-02T00:51:00.385Z - info: VirtualBox Version: 4.3.6r91406

2014-08-02T00:51:00.385Z - info: Vagrant Version: Vagrant 1.4.3

2014-08-02T00:51:00.385Z - info: Installation completed successfully.
2014-08-02T00:51:01.095Z - info: Existing VirtualBox installation, version 4.3.6
2014-08-02T00:51:01.096Z - info: Existing Vagrant installation, version 1.4.3
2014-08-02T00:51:01.103Z - info: Kalabox image already downloaded.
2014-08-02T00:51:01.103Z - info: Box image downloaded.
2014-08-02T00:51:01.104Z - info: Kalastack already downloaded
2014-08-02T00:51:01.104Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-08-02T00:51:01.604Z - info: Kalastack downloaded
2014-08-02T00:51:01.605Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-08-02T00:51:05.585Z - info: Wrote configuration file.
2014-08-02T00:51:05.615Z - info: Executing box spinup.
2014-08-02T00:51:05.655Z - info: Starting spinup attempt 0
2014-08-02T00:51:07.139Z - info: Box initialized.
2014-08-02T00:51:07.139Z - info: Kalabox Version: 1.0-beta7
2014-08-02T00:51:07.140Z - info: Mac OS Version: 10.9.4

2014-08-02T00:51:07.140Z - info: VirtualBox Version: 4.3.6r91406

2014-08-02T00:51:07.140Z - info: Vagrant Version: Vagrant 1.4.3

2014-08-02T00:51:07.140Z - info: Installation completed successfully.
2014-08-02T01:25:01.209Z - warn: An error occurred in an async call.
cause stack is ...
  Error: Command failed: Authentication failed. Please check your credentials and try again.      [error]

```
at ChildProcess.exithandler (child_process.js:661:12)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Process.ChildProcess._handle.onexit (child_process.js:840:5)
```

async call history is ...
 [ { function: 'authenticate2',
    location: '/private/var/folders/9y/56lcg_r96s7b28bjdgrr0bzm0000gn/T/.org.chromium.Chromium.FE9hmG/kalabox/utils/pantheon-auth.js:93:76',
    mapping: { description: 'tail' } } ]
2014-08-02T01:25:32.579Z - warn: An error occurred in an async call.
cause stack is ...
  Error: Command failed: Authentication failed. Please check your credentials and try again.      [error]

```
at ChildProcess.exithandler (child_process.js:661:12)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Process.ChildProcess._handle.onexit (child_process.js:840:5)
```

async call history is ...
 [ { function: 'authenticate2',
    location: '/private/var/folders/9y/56lcg_r96s7b28bjdgrr0bzm0000gn/T/.org.chromium.Chromium.FE9hmG/kalabox/utils/pantheon-auth.js:93:76',
    mapping: { description: 'tail' } } ]
2014-08-04T00:23:24.742Z - info: Box initialized.
2014-08-04T00:23:24.743Z - info: Kalabox Version: 1.0-beta7
2014-08-04T00:23:24.743Z - info: Mac OS Version: 10.9.4

2014-08-04T00:23:24.743Z - info: VirtualBox Version: 4.3.6r91406

2014-08-04T00:23:24.743Z - info: Vagrant Version: Vagrant 1.4.3

2014-08-04T00:25:35.161Z - warn: An error occurred in an async call.
cause stack is ...
  Error: Command failed: Authentication failed. Please check your credentials and try again.      [error]

```
at ChildProcess.exithandler (child_process.js:661:12)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Socket.eval (child_process.js:994:11)
at Socket.EventEmitter.emit (events.js:98:17)
at Pipe.eval [as close] (net.js:459:12)
```

async call history is ...
 [ { function: 'authenticate2',
    location: '/private/var/folders/9y/56lcg_r96s7b28bjdgrr0bzm0000gn/T/.org.chromium.Chromium.D4Cyti/kalabox/utils/pantheon-auth.js:93:76',
    mapping: { description: 'tail' } } ]
2014-08-04T00:25:46.166Z - warn: An error occurred in an async call.
cause stack is ...
  Error: Command failed: A valid email address is required to authenticate.                       [error]

```
at ChildProcess.exithandler (child_process.js:661:12)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Socket.eval (child_process.js:994:11)
at Socket.EventEmitter.emit (events.js:98:17)
at Pipe.eval [as close] (net.js:459:12)
```

async call history is ...
 [ { function: 'authenticate2',
    location: '/private/var/folders/9y/56lcg_r96s7b28bjdgrr0bzm0000gn/T/.org.chromium.Chromium.D4Cyti/kalabox/utils/pantheon-auth.js:93:76',
    mapping: { description: 'tail' } } ]
2014-08-04T00:26:26.077Z - warn: An error occurred in an async call.
cause stack is ...
  Error: Command failed: Authentication failed. Please check your credentials and try again.      [error]

```
at ChildProcess.exithandler (child_process.js:661:12)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Process.ChildProcess._handle.onexit (child_process.js:840:5)
```

async call history is ...
 [ { function: 'authenticate2',
    location: '/private/var/folders/9y/56lcg_r96s7b28bjdgrr0bzm0000gn/T/.org.chromium.Chromium.D4Cyti/kalabox/utils/pantheon-auth.js:93:76',
    mapping: { description: 'tail' } } ]
2014-08-04T00:27:11.602Z - warn: An error occurred in an async call.
cause stack is ...
  Error: Command failed: Authentication failed. Please check your credentials and try again.      [error]

```
at ChildProcess.exithandler (child_process.js:661:12)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Socket.eval (child_process.js:994:11)
at Socket.EventEmitter.emit (events.js:98:17)
at Pipe.eval [as close] (net.js:459:12)
```

async call history is ...
 [ { function: 'authenticate2',
    location: '/private/var/folders/9y/56lcg_r96s7b28bjdgrr0bzm0000gn/T/.org.chromium.Chromium.D4Cyti/kalabox/utils/pantheon-auth.js:93:76',
    mapping: { description: 'tail' } } ]
2014-08-04T00:30:17.128Z - warn: An error occurred in an async call.
cause stack is ...
  Error: Command failed: Authentication failed. Please check your credentials and try again.      [error]

```
at ChildProcess.exithandler (child_process.js:661:12)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Socket.eval (child_process.js:994:11)
at Socket.EventEmitter.emit (events.js:98:17)
at Pipe.eval [as close] (net.js:459:12)
```

async call history is ...
 [ { function: 'authenticate2',
    location: '/private/var/folders/9y/56lcg_r96s7b28bjdgrr0bzm0000gn/T/.org.chromium.Chromium.D4Cyti/kalabox/utils/pantheon-auth.js:93:76',
    mapping: { description: 'tail' } } ]
2014-08-04T00:32:29.874Z - error: An error occurred in an async call.
cause stack is ...
  Error: Command failed: No user UUID found. Please authenticate first using 'drush pauth'        [error]
Connection to 127.0.0.1 closed by remote host.

```
at ChildProcess.exithandler (child_process.js:661:12)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Socket.eval (child_process.js:994:11)
at Socket.EventEmitter.emit (events.js:98:17)
at Pipe.eval [as close] (net.js:459:12)
```

async call history is ...
 [ { function: 'startBox4',
    location: '/private/var/folders/9y/56lcg_r96s7b28bjdgrr0bzm0000gn/T/.org.chromium.Chromium.D4Cyti/kalabox/box.js:168:108',
    mapping: { description: 'tail' } } ]
##

**Comment by pirog** [comment]
@ocompagne can you give a little more detail around your issue? what are you trying to do when it errs?

**Comment by oliviercp** [comment]
Sorry - I was just following the instructions in the Kalabox software to paste the content of the error message on this board. I'm not really looking for help. 

But yes I can give more details if that's helpful: I was simply closing Kalabox, and I got this error message. As I read the error, it seemed like an authentification error, which made sense because I hadn't been able to sign in with my Pantheon account (due to another bug when there are special characters in the password...). However, I later found a way to sign in to Kalabox with my Pantheon account, and yet I got this apparently same error again...

**Comment by pirog** [comment]
What are you doing when you "close" kalabox? are you going to File -> Exit? Or using some other mechanism?

**Comment by oliviercp** [comment]
I click the red close button in the corner of the window.

_Olivier CompagneSee my roles »
https://glassfrog.holacracy.org/people/916_
Schedule time with me http://meetme.so/oliviercompagneh1
HolacracyOne, LLC
holacracy.org
[image: Facebook] http://www.facebook.com/holacracyone [image: Twitter]
http://www.twitter.com/holacracyone [image: YouTube]
http://www.youtube.com/holacracyone

**Comment by pirog** [comment]
interesting. thanks for letting us know and we will try to see if we can replicate this error.
