### ISSUE TITLE
Does not start.

### ISSUE THREAD

**Issue by imgio** [kalamuna/kalaboxv1#111]
### Kalabox Log

2014-08-04T16:42:18.542Z - info: Box initialized.
2014-08-04T16:42:18.547Z - info: Kalabox Version: 1.0-beta7
2014-08-04T16:42:18.548Z - info: Mac OS Version: 10.6.8

2014-08-04T16:42:18.548Z - info: VirtualBox Version: 4.2.14r86644

2014-08-04T16:42:18.548Z - info: Vagrant Version: false
2014-08-04T16:42:36.761Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Command failed: sudo-pass.scpt:169:223: execution error: File alias HD:private:var:folders:YL:YLUNLAcLFBi6gEEwhnq-Sk+++TQ:-Tmp-:.org.chromium.Chromium.e1A0Vy:kalabox:utils:task-runner:sudo-pass.scpt:..:..:..:..:app.icns of «script» wasn’t found. (-43)

```
at ChildProcess.exithandler (child_process.js:661:12)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Socket.eval (child_process.js:994:11)
at Socket.EventEmitter.emit (events.js:98:17)
at Pipe.eval [as close] (net.js:459:12)
```

async call history is ...
 [ { function: 'getPassword0',
    location: '/private/var/folders/YL/YLUNLAcLFBi6gEEwhnq-Sk+++TQ/-Tmp-/.org.chromium.Chromium.e1A0Vy/kalabox/utils/task-runner/sudo-runner.js:160:61',
    mapping: { description: 'tail' } },
  { function: 'runCommand1',
    location: '/private/var/folders/YL/YLUNLAcLFBi6gEEwhnq-Sk+++TQ/-Tmp-/.org.chromium.Chromium.e1A0Vy/kalabox/utils/task-runner/sudo-runner.js:49:24',
    mapping: { description: 'tail' } },
  { function: 'installGetPassword',
    location: '/private/var/folders/YL/YLUNLAcLFBi6gEEwhnq-Sk+++TQ/-Tmp-/.org.chromium.Chromium.e1A0Vy/kalabox/installer/installer.js:263:71',
    mapping: { description: 'tail' } } ]
2014-08-04T16:43:10.816Z - info: Box initialized.
2014-08-04T16:43:10.819Z - info: Kalabox Version: 1.0-beta7
2014-08-04T16:43:10.820Z - info: Mac OS Version: 10.6.8

2014-08-04T16:43:10.820Z - info: VirtualBox Version: 4.2.14r86644

2014-08-04T16:43:10.820Z - info: Vagrant Version: false
2014-08-04T16:43:15.034Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Command failed: sudo-pass.scpt:169:223: execution error: File alias HD:private:var:folders:YL:YLUNLAcLFBi6gEEwhnq-Sk+++TQ:-Tmp-:.org.chromium.Chromium.vwJH4Q:kalabox:utils:task-runner:sudo-pass.scpt:..:..:..:..:app.icns of «script» wasn’t found. (-43)

```
at ChildProcess.exithandler (child_process.js:661:12)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Socket.eval (child_process.js:994:11)
at Socket.EventEmitter.emit (events.js:98:17)
at Pipe.eval [as close] (net.js:459:12)
```

async call history is ...
 [ { function: 'getPassword0',
    location: '/private/var/folders/YL/YLUNLAcLFBi6gEEwhnq-Sk+++TQ/-Tmp-/.org.chromium.Chromium.vwJH4Q/kalabox/utils/task-runner/sudo-runner.js:160:61',
    mapping: { description: 'tail' } },
  { function: 'runCommand1',
    location: '/private/var/folders/YL/YLUNLAcLFBi6gEEwhnq-Sk+++TQ/-Tmp-/.org.chromium.Chromium.vwJH4Q/kalabox/utils/task-runner/sudo-runner.js:49:24',
    mapping: { description: 'tail' } },
  { function: 'installGetPassword',
    location: '/private/var/folders/YL/YLUNLAcLFBi6gEEwhnq-Sk+++TQ/-Tmp-/.org.chromium.Chromium.vwJH4Q/kalabox/installer/installer.js:263:71',
    mapping: { description: 'tail' } } ]
##

**Comment by pirog** [comment]
Issue here is that Kalabox does not work on OSX below 10.7 :(

We should make sure this is clearly stated in teh readme or otherwise.
