### ISSUE TITLE
Error when spinning up: can't detect VirtualBox

### ISSUE THREAD

**Issue by dsquaredb** [kalamuna/kalaboxv1#112]
Here is the message I get when attempting to spin up a box on a new MacBook Pro running OS X 10.9.4:
### Kalabox Log

2014-08-05T23:45:58.887Z - info: Box initialized.
2014-08-05T23:45:58.888Z - info: Kalabox Version: 1.0-beta7
2014-08-05T23:45:58.888Z - info: Mac OS Version: 10.9.4

2014-08-05T23:45:58.888Z - info: VirtualBox Version: false
2014-08-05T23:45:58.888Z - info: Vagrant Version: false
2014-08-05T23:46:02.164Z - info: VirtualBox not installed or wrong version. Installing.
2014-08-05T23:46:02.165Z - info: User granted permission to install VirtualBox
2014-08-05T23:48:03.540Z - info: Successfully downloaded VirtualBox DMG.
2014-08-05T23:48:16.261Z - info: Successfully mounted VirtualBox DMG.
2014-08-05T23:48:16.493Z - info: VirtualBox installation complete.
2014-08-05T23:48:16.607Z - info: Successfully ejected VirtualBox DMG.
2014-08-05T23:48:16.607Z - info: Vagrant not installed or wrong version. Installing.
2014-08-05T23:48:16.608Z - info: User granted permission to install Vagrant
2014-08-05T23:48:50.567Z - info: Successfully downloaded Vagrant DMG.
2014-08-05T23:48:55.086Z - info: Successfully mounted Vagrant DMG.
2014-08-05T23:49:02.667Z - info: Vagrant installation complete.
2014-08-05T23:49:02.782Z - info: Successfully ejected Vagrant DMG.
2014-08-05T23:49:02.789Z - info: Kalabox image already downloaded.
2014-08-05T23:49:02.790Z - info: Box image downloaded.
2014-08-05T23:49:03.124Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-08-05T23:49:04.104Z - info: Kalastack downloaded
2014-08-05T23:49:04.105Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-08-05T23:49:12.748Z - info: Adding base box image to Vagrant.
2014-08-05T23:49:22.327Z - info: Wrote configuration file.
2014-08-05T23:49:22.388Z - info: Executing box spinup.
2014-08-05T23:49:22.423Z - info: Starting spinup attempt 0
2014-08-05T23:49:23.234Z - warn: Spinup attempt 0 failed with error: Command failed: Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.

2014-08-05T23:49:23.886Z - info: Starting spinup attempt 1
2014-08-05T23:49:24.505Z - warn: Spinup attempt 1 failed with error: Command failed: Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.

2014-08-05T23:49:25.173Z - info: Starting spinup attempt 2
2014-08-05T23:49:25.860Z - warn: Spinup attempt 2 failed with error: Command failed: Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.

2014-08-05T23:49:26.567Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Failed to spin up virtual machine after 3 attempts. Error was: Command failed: Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.

```
at eval (/private/var/folders/dp/dq7nrb9n45s2wjxmb5tr_85h0000gn/T/.org.chromium.Chromium.pJ6b7X/kalabox/installer/install-utils.js:359:22)
at ChildProcess.exithandler (child_process.js:665:7)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Socket.eval (child_process.js:994:11)
at Socket.EventEmitter.emit (events.js:98:17)
at Pipe.eval [as close] (net.js:459:12)
```

async call history is ...
 [ { function: 'install16',
    location: '/private/var/folders/dp/dq7nrb9n45s2wjxmb5tr_85h0000gn/T/.org.chromium.Chromium.pJ6b7X/kalabox/installer/installer.js:484:33',
    mapping: { description: 'tail' } } ]
##

**Comment by pirog** [comment]
If you look in your applications folder can you see VirtualBox?

**Comment by dsquaredb** [comment]
Thanks for the quick response. I am away from my computer this evening. I'll take a look tomorrow and get back to you.

**Comment by dsquaredb** [comment]
I checked my applications folder and do not see VirtualBox.

**Comment by dsquaredb** [comment]
Hey Mike,

Just an update... After several failed attempts to spin up Kalabox again this morning, I rebooted my computer and tried one more time. Success. Everything seems to be working fine now.

Not sure what the problem was exactly, but  when I used the uninstaller, I saw a message about running VirtualBox instances. So, I tried the reboot to see if it would stop them and it worked.

**Comment by dsquaredb** [comment]
Hey Mike,

Sorry to bother you, but still having a little problem with Kalabox. I got everything to install and it is working well - except that one of my sites from Pantheon won’t open. I downloaded all my Pantheon sites with Kalabox and all the others are fine. But the one that won’t open just goes to my ISPs page saying the website can’t be found.

I checked and the database and the code and files look like they have downloaded okay, so not sure what is happening. I tried removing that one site and then adding it again, but that doesn’t do anything either. Of course, this is the main site I need to access. :)

Any thoughts?

Danita

**Comment by pirog** [comment]
No worries. I would check two things.
1. Open a Mac Terminal and paste the output of `/etc/hosts` here by running `cat /etc/hosts`. Do you see your site listed there?
2. Check this issue to see if your ISP is just hijacking your DNS https://github.com/kalamuna/kalabox/issues/11

**Comment by dsquaredb** [comment]
I checked the output /etc/hosts and can see all of my Pantheon sites listed I have downloaded except for the one that is not behaving. All of the ones that I see are working fine.

I haven’t checked the DNS hijacking since all of the other sites seem to be fine.

**Comment by pirog** [comment]
Well that will do it! Def needs to be in /etc/hosts. Usually this is an indication that your site did not build properly. What i would do is delete the site (make sure you delete the code folder on your Mac as well) and then ssh into the box and run the following command

`drush pullsite SITENAME.dev --debug --verbose`

this should give you a good error message to help you debug.
