### ISSUE TITLE
Uh oh... when installing beta8 on new machine.

### ISSUE THREAD

**Issue by pi-ron** [kalamuna/kalaboxv1#116]
Hi Mike,

I'm doing a fresh install of beta8 on a new machine. After clicking 'Box me' I haven't been watching the process, just opened it up and there is a white screen – I hadn't copied the app to my Applications folder, not sure if that matters.

Copied to my apps folder, re-opened and got this:
### Kalabox Log

```
2014-08-08T03:18:26.074Z - info: Box initialized.
2014-08-08T03:18:26.075Z - info: Kalabox Version: 1.0-beta7
2014-08-08T03:18:26.075Z - info: Mac OS Version: 10.9.2

2014-08-08T03:18:26.075Z - info: VirtualBox Version: 4.3.6r91406

2014-08-08T03:18:26.075Z - info: Vagrant Version: Vagrant 1.4.3

2014-08-08T03:18:28.815Z - info: Existing VirtualBox installation, version 4.3.6
2014-08-08T03:18:28.816Z - info: Existing Vagrant installation, version 1.4.3
2014-08-08T03:18:28.822Z - info: Kalabox image already downloaded.
2014-08-08T03:18:28.823Z - info: Box image downloaded.
2014-08-08T03:18:28.824Z - info: Kalastack already downloaded
2014-08-08T03:18:28.825Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-08-08T03:18:29.456Z - info: Kalastack downloaded
2014-08-08T03:18:29.457Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-08-08T03:18:46.061Z - info: Adding base box image to Vagrant.
2014-08-08T03:19:00.043Z - info: Wrote configuration file.
2014-08-08T03:19:00.092Z - info: Executing box spinup.
2014-08-08T03:19:00.123Z - info: Starting spinup attempt 0
2014-08-08T03:19:00.620Z - warn: Spinup attempt 0 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-08-08T03:19:01.128Z - info: Starting spinup attempt 1
2014-08-08T03:19:01.605Z - warn: Spinup attempt 1 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-08-08T03:19:02.100Z - info: Starting spinup attempt 2
2014-08-08T03:19:02.577Z - warn: Spinup attempt 2 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-08-08T03:19:03.053Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Failed to spin up virtual machine after 3 attempts. Error was: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

    at eval (/private/var/folders/xd/cj9dhbfd2z5cqwdfvly6qyzm0000gn/T/.org.chromium.Chromium.Ny2TPi/kalabox/installer/install-utils.js:359:22)
    at ChildProcess.exithandler (child_process.js:665:7)
    at ChildProcess.EventEmitter.emit (events.js:101:17)
    at maybeClose (child_process.js:773:16)
    at Socket.eval (child_process.js:994:11)
    at Socket.EventEmitter.emit (events.js:98:17)
    at Pipe.eval [as close] (net.js:459:12)
async call history is ...
 [ { function: 'install16',
    location: '/private/var/folders/xd/cj9dhbfd2z5cqwdfvly6qyzm0000gn/T/.org.chromium.Chromium.Ny2TPi/kalabox/installer/installer.js:484:33',
    mapping: { description: 'tail' } } ]
```
##

**Comment by pi-ron** [comment]
Ran uninstall tool option 1, reopened Kalabox, clicked 'Box Me'

### Kalabox Log

```
2014-08-08T03:18:26.074Z - info: Box initialized.
2014-08-08T03:18:26.075Z - info: Kalabox Version: 1.0-beta7
2014-08-08T03:18:26.075Z - info: Mac OS Version: 10.9.2

2014-08-08T03:18:26.075Z - info: VirtualBox Version: 4.3.6r91406

2014-08-08T03:18:26.075Z - info: Vagrant Version: Vagrant 1.4.3

2014-08-08T03:18:28.815Z - info: Existing VirtualBox installation, version 4.3.6
2014-08-08T03:18:28.816Z - info: Existing Vagrant installation, version 1.4.3
2014-08-08T03:18:28.822Z - info: Kalabox image already downloaded.
2014-08-08T03:18:28.823Z - info: Box image downloaded.
2014-08-08T03:18:28.824Z - info: Kalastack already downloaded
2014-08-08T03:18:28.825Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-08-08T03:18:29.456Z - info: Kalastack downloaded
2014-08-08T03:18:29.457Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-08-08T03:18:46.061Z - info: Adding base box image to Vagrant.
2014-08-08T03:19:00.043Z - info: Wrote configuration file.
2014-08-08T03:19:00.092Z - info: Executing box spinup.
2014-08-08T03:19:00.123Z - info: Starting spinup attempt 0
2014-08-08T03:19:00.620Z - warn: Spinup attempt 0 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-08-08T03:19:01.128Z - info: Starting spinup attempt 1
2014-08-08T03:19:01.605Z - warn: Spinup attempt 1 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-08-08T03:19:02.100Z - info: Starting spinup attempt 2
2014-08-08T03:19:02.577Z - warn: Spinup attempt 2 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-08-08T03:19:03.053Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Failed to spin up virtual machine after 3 attempts. Error was: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

    at eval (/private/var/folders/xd/cj9dhbfd2z5cqwdfvly6qyzm0000gn/T/.org.chromium.Chromium.Ny2TPi/kalabox/installer/install-utils.js:359:22)
    at ChildProcess.exithandler (child_process.js:665:7)
    at ChildProcess.EventEmitter.emit (events.js:101:17)
    at maybeClose (child_process.js:773:16)
    at Socket.eval (child_process.js:994:11)
    at Socket.EventEmitter.emit (events.js:98:17)
    at Pipe.eval [as close] (net.js:459:12)
async call history is ...
 [ { function: 'install16',
    location: '/private/var/folders/xd/cj9dhbfd2z5cqwdfvly6qyzm0000gn/T/.org.chromium.Chromium.Ny2TPi/kalabox/installer/installer.js:484:33',
    mapping: { description: 'tail' } } ]
2014-08-08T03:22:01.316Z - info: Box initialized.
2014-08-08T03:22:01.317Z - info: Kalabox Version: 1.0-beta7
2014-08-08T03:22:01.317Z - info: Mac OS Version: 10.9.2

2014-08-08T03:22:01.317Z - info: VirtualBox Version: 4.3.6r91406

2014-08-08T03:22:01.317Z - info: Vagrant Version: Vagrant 1.4.3

2014-08-08T03:22:06.752Z - info: Existing VirtualBox installation, version 4.3.6
2014-08-08T03:22:06.752Z - info: Existing Vagrant installation, version 1.4.3
2014-08-08T03:22:06.759Z - info: Kalabox image already downloaded.
2014-08-08T03:22:06.759Z - info: Box image downloaded.
2014-08-08T03:22:06.761Z - info: Kalastack already downloaded
2014-08-08T03:22:06.761Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-08-08T03:22:07.406Z - info: Kalastack downloaded
2014-08-08T03:22:07.406Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-08-08T03:22:21.897Z - info: Wrote configuration file.
2014-08-08T03:22:21.928Z - info: Executing box spinup.
2014-08-08T03:22:21.958Z - info: Starting spinup attempt 0
2014-08-08T03:22:22.432Z - warn: Spinup attempt 0 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-08-08T03:22:22.934Z - info: Starting spinup attempt 1
2014-08-08T03:22:23.418Z - warn: Spinup attempt 1 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-08-08T03:22:23.923Z - info: Starting spinup attempt 2
2014-08-08T03:22:24.401Z - warn: Spinup attempt 2 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-08-08T03:22:24.871Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Failed to spin up virtual machine after 3 attempts. Error was: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

    at eval (/private/var/folders/xd/cj9dhbfd2z5cqwdfvly6qyzm0000gn/T/.org.chromium.Chromium.KYAsdL/kalabox/installer/install-utils.js:359:22)
    at ChildProcess.exithandler (child_process.js:665:7)
    at ChildProcess.EventEmitter.emit (events.js:101:17)
    at maybeClose (child_process.js:773:16)
    at Socket.eval (child_process.js:994:11)
    at Socket.EventEmitter.emit (events.js:98:17)
    at Pipe.eval [as close] (net.js:459:12)
async call history is ...
 [ { function: 'install16',
    location: '/private/var/folders/xd/cj9dhbfd2z5cqwdfvly6qyzm0000gn/T/.org.chromium.Chromium.KYAsdL/kalabox/installer/installer.js:484:33',
    mapping: { description: 'tail' } } ]
```

**Comment by pi-ron** [comment]
Ran uninstall tool Option 2 and got Uh oh...

### Kalabox Log

```
2014-08-08T03:18:26.074Z - info: Box initialized.
2014-08-08T03:18:26.075Z - info: Kalabox Version: 1.0-beta7
2014-08-08T03:18:26.075Z - info: Mac OS Version: 10.9.2

2014-08-08T03:18:26.075Z - info: VirtualBox Version: 4.3.6r91406

2014-08-08T03:18:26.075Z - info: Vagrant Version: Vagrant 1.4.3

2014-08-08T03:18:28.815Z - info: Existing VirtualBox installation, version 4.3.6
2014-08-08T03:18:28.816Z - info: Existing Vagrant installation, version 1.4.3
2014-08-08T03:18:28.822Z - info: Kalabox image already downloaded.
2014-08-08T03:18:28.823Z - info: Box image downloaded.
2014-08-08T03:18:28.824Z - info: Kalastack already downloaded
2014-08-08T03:18:28.825Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-08-08T03:18:29.456Z - info: Kalastack downloaded
2014-08-08T03:18:29.457Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-08-08T03:18:46.061Z - info: Adding base box image to Vagrant.
2014-08-08T03:19:00.043Z - info: Wrote configuration file.
2014-08-08T03:19:00.092Z - info: Executing box spinup.
2014-08-08T03:19:00.123Z - info: Starting spinup attempt 0
2014-08-08T03:19:00.620Z - warn: Spinup attempt 0 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-08-08T03:19:01.128Z - info: Starting spinup attempt 1
2014-08-08T03:19:01.605Z - warn: Spinup attempt 1 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-08-08T03:19:02.100Z - info: Starting spinup attempt 2
2014-08-08T03:19:02.577Z - warn: Spinup attempt 2 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-08-08T03:19:03.053Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Failed to spin up virtual machine after 3 attempts. Error was: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

    at eval (/private/var/folders/xd/cj9dhbfd2z5cqwdfvly6qyzm0000gn/T/.org.chromium.Chromium.Ny2TPi/kalabox/installer/install-utils.js:359:22)
    at ChildProcess.exithandler (child_process.js:665:7)
    at ChildProcess.EventEmitter.emit (events.js:101:17)
    at maybeClose (child_process.js:773:16)
    at Socket.eval (child_process.js:994:11)
    at Socket.EventEmitter.emit (events.js:98:17)
    at Pipe.eval [as close] (net.js:459:12)
async call history is ...
 [ { function: 'install16',
    location: '/private/var/folders/xd/cj9dhbfd2z5cqwdfvly6qyzm0000gn/T/.org.chromium.Chromium.Ny2TPi/kalabox/installer/installer.js:484:33',
    mapping: { description: 'tail' } } ]
2014-08-08T03:22:01.316Z - info: Box initialized.
2014-08-08T03:22:01.317Z - info: Kalabox Version: 1.0-beta7
2014-08-08T03:22:01.317Z - info: Mac OS Version: 10.9.2

2014-08-08T03:22:01.317Z - info: VirtualBox Version: 4.3.6r91406

2014-08-08T03:22:01.317Z - info: Vagrant Version: Vagrant 1.4.3

2014-08-08T03:22:06.752Z - info: Existing VirtualBox installation, version 4.3.6
2014-08-08T03:22:06.752Z - info: Existing Vagrant installation, version 1.4.3
2014-08-08T03:22:06.759Z - info: Kalabox image already downloaded.
2014-08-08T03:22:06.759Z - info: Box image downloaded.
2014-08-08T03:22:06.761Z - info: Kalastack already downloaded
2014-08-08T03:22:06.761Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-08-08T03:22:07.406Z - info: Kalastack downloaded
2014-08-08T03:22:07.406Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-08-08T03:22:21.897Z - info: Wrote configuration file.
2014-08-08T03:22:21.928Z - info: Executing box spinup.
2014-08-08T03:22:21.958Z - info: Starting spinup attempt 0
2014-08-08T03:22:22.432Z - warn: Spinup attempt 0 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-08-08T03:22:22.934Z - info: Starting spinup attempt 1
2014-08-08T03:22:23.418Z - warn: Spinup attempt 1 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-08-08T03:22:23.923Z - info: Starting spinup attempt 2
2014-08-08T03:22:24.401Z - warn: Spinup attempt 2 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-08-08T03:22:24.871Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Failed to spin up virtual machine after 3 attempts. Error was: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

    at eval (/private/var/folders/xd/cj9dhbfd2z5cqwdfvly6qyzm0000gn/T/.org.chromium.Chromium.KYAsdL/kalabox/installer/install-utils.js:359:22)
    at ChildProcess.exithandler (child_process.js:665:7)
    at ChildProcess.EventEmitter.emit (events.js:101:17)
    at maybeClose (child_process.js:773:16)
    at Socket.eval (child_process.js:994:11)
    at Socket.EventEmitter.emit (events.js:98:17)
    at Pipe.eval [as close] (net.js:459:12)
async call history is ...
 [ { function: 'install16',
    location: '/private/var/folders/xd/cj9dhbfd2z5cqwdfvly6qyzm0000gn/T/.org.chromium.Chromium.KYAsdL/kalabox/installer/installer.js:484:33',
    mapping: { description: 'tail' } } ]
2014-08-08T03:24:55.145Z - info: Box initialized.
2014-08-08T03:24:55.146Z - info: Kalabox Version: 1.0-beta7
2014-08-08T03:24:55.146Z - info: Mac OS Version: 10.9.2

2014-08-08T03:24:55.146Z - info: VirtualBox Version: false
2014-08-08T03:24:55.146Z - info: Vagrant Version: false
2014-08-08T03:24:58.133Z - info: VirtualBox not installed or wrong version. Installing.
2014-08-08T03:24:58.134Z - info: User granted permission to install VirtualBox
2014-08-08T03:30:56.345Z - info: Successfully downloaded VirtualBox DMG.
2014-08-08T03:31:07.169Z - info: Successfully mounted VirtualBox DMG.
2014-08-08T03:31:22.466Z - info: VirtualBox installation complete.
2014-08-08T03:31:22.568Z - info: Successfully ejected VirtualBox DMG.
2014-08-08T03:31:22.569Z - info: Vagrant not installed or wrong version. Installing.
2014-08-08T03:31:22.569Z - info: User granted permission to install Vagrant
2014-08-08T03:32:42.068Z - info: Successfully downloaded Vagrant DMG.
2014-08-08T03:32:47.078Z - info: Successfully mounted Vagrant DMG.
2014-08-08T03:32:53.967Z - info: Vagrant installation complete.
2014-08-08T03:32:54.049Z - info: Successfully ejected Vagrant DMG.
2014-08-08T03:32:54.057Z - info: Kalabox image already downloaded.
2014-08-08T03:32:54.057Z - info: Box image downloaded.
2014-08-08T03:32:54.058Z - info: Kalastack already downloaded
2014-08-08T03:32:54.058Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-08-08T03:32:54.919Z - info: Kalastack downloaded
2014-08-08T03:32:54.920Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-08-08T03:33:16.934Z - info: Wrote configuration file.
2014-08-08T03:33:16.966Z - info: Executing box spinup.
2014-08-08T03:33:17.000Z - info: Starting spinup attempt 0
2014-08-08T03:33:17.509Z - warn: Spinup attempt 0 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-08-08T03:33:18.023Z - info: Starting spinup attempt 1
2014-08-08T03:33:18.708Z - warn: Spinup attempt 1 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-08-08T03:33:19.222Z - info: Starting spinup attempt 2
2014-08-08T03:33:19.709Z - warn: Spinup attempt 2 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-08-08T03:33:20.214Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Failed to spin up virtual machine after 3 attempts. Error was: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

    at eval (/private/var/folders/xd/cj9dhbfd2z5cqwdfvly6qyzm0000gn/T/.org.chromium.Chromium.Ww9XMI/kalabox/installer/install-utils.js:359:22)
    at ChildProcess.exithandler (child_process.js:665:7)
    at ChildProcess.EventEmitter.emit (events.js:101:17)
    at maybeClose (child_process.js:773:16)
    at Socket.eval (child_process.js:994:11)
    at Socket.EventEmitter.emit (events.js:98:17)
    at Pipe.eval [as close] (net.js:459:12)
async call history is ...
 [ { function: 'install16',
    location: '/private/var/folders/xd/cj9dhbfd2z5cqwdfvly6qyzm0000gn/T/.org.chromium.Chromium.Ww9XMI/kalabox/installer/installer.js:484:33',
    mapping: { description: 'tail' } } ]
```

**Comment by pirog** [comment]
I would def recommend moving the application to your applications folder! I
think that is critical. I would also use option #2 if possible for the full
clean.

On Thu, Aug 7, 2014 at 8:29 PM, Tigeda notifications@github.com wrote:

> Ran uninstall tool option 1, reopened Kalabox, clicked 'Box Me'
> Kalabox Log
> 
> 2014-08-08T03:18:26.074Z - info: Box initialized.
> 2014-08-08T03:18:26.075Z - info: Kalabox Version: 1.0-beta7
> 2014-08-08T03:18:26.075Z - info: Mac OS Version: 10.9.2
> 
> 2014-08-08T03:18:26.075Z - info: VirtualBox Version: 4.3.6r91406
> 
> 2014-08-08T03:18:26.075Z - info: Vagrant Version: Vagrant 1.4.3
> 
> 2014-08-08T03:18:28.815Z - info: Existing VirtualBox installation, version 4.3.6
> 2014-08-08T03:18:28.816Z - info: Existing Vagrant installation, version 1.4.3
> 2014-08-08T03:18:28.822Z - info: Kalabox image already downloaded.
> 2014-08-08T03:18:28.823Z - info: Box image downloaded.
> 2014-08-08T03:18:28.824Z - info: Kalastack already downloaded
> 2014-08-08T03:18:28.825Z - info: Installing Vagrant plugin vagrant-hostsupdater
> 2014-08-08T03:18:29.456Z - info: Kalastack downloaded
> 2014-08-08T03:18:29.457Z - info: Installing Vagrant plugin vagrant-hostsupdater
> 2014-08-08T03:18:46.061Z - info: Adding base box image to Vagrant.
> 2014-08-08T03:19:00.043Z - info: Wrote configuration file.
> 2014-08-08T03:19:00.092Z - info: Executing box spinup.
> 2014-08-08T03:19:00.123Z - info: Starting spinup attempt 0
> 2014-08-08T03:19:00.620Z - warn: Spinup attempt 0 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
> to set one up in this directory, or change to a directory with a
> Vagrantfile and try again.
> 
> 2014-08-08T03:19:01.128Z - info: Starting spinup attempt 1
> 2014-08-08T03:19:01.605Z - warn: Spinup attempt 1 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
> to set one up in this directory, or change to a directory with a
> Vagrantfile and try again.
> 
> 2014-08-08T03:19:02.100Z - info: Starting spinup attempt 2
> 2014-08-08T03:19:02.577Z - warn: Spinup attempt 2 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
> to set one up in this directory, or change to a directory with a
> Vagrantfile and try again.
> 
> 2014-08-08T03:19:03.053Z - error: Error during installation routine: An error occurred in an async call.
> cause stack is ...
>   Error: Failed to spin up virtual machine after 3 attempts. Error was: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
> to set one up in this directory, or change to a directory with a
> Vagrantfile and try again.
> 
> ```
> at eval (/private/var/folders/xd/cj9dhbfd2z5cqwdfvly6qyzm0000gn/T/.org.chromium.Chromium.Ny2TPi/kalabox/installer/install-utils.js:359:22)
> at ChildProcess.exithandler (child_process.js:665:7)
> at ChildProcess.EventEmitter.emit (events.js:101:17)
> at maybeClose (child_process.js:773:16)
> at Socket.eval (child_process.js:994:11)
> at Socket.EventEmitter.emit (events.js:98:17)
> at Pipe.eval [as close] (net.js:459:12)
> ```
> 
> async call history is ...
>  [ { function: 'install16',
>     location: '/private/var/folders/xd/cj9dhbfd2z5cqwdfvly6qyzm0000gn/T/.org.chromium.Chromium.Ny2TPi/kalabox/installer/
> installer.js:484:33',
>     mapping: { description: 'tail' } } ]
> 2014-08-08T03:22:01.316Z - info: Box initialized.
> 2014-08-08T03:22:01.317Z - info: Kalabox Version: 1.0-beta7
> 2014-08-08T03:22:01.317Z - info: Mac OS Version: 10.9.2
> 
> 2014-08-08T03:22:01.317Z - info: VirtualBox Version: 4.3.6r91406
> 
> 2014-08-08T03:22:01.317Z - info: Vagrant Version: Vagrant 1.4.3
> 
> 2014-08-08T03:22:06.752Z - info: Existing VirtualBox installation, version 4.3.6
> 2014-08-08T03:22:06.752Z - info: Existing Vagrant installation, version 1.4.3
> 2014-08-08T03:22:06.759Z - info: Kalabox image already downloaded.
> 2014-08-08T03:22:06.759Z - info: Box image downloaded.
> 2014-08-08T03:22:06.761Z - info: Kalastack already downloaded
> 2014-08-08T03:22:06.761Z - info: Installing Vagrant plugin vagrant-hostsupdater
> 2014-08-08T03:22:07.406Z - info: Kalastack downloaded
> 2014-08-08T03:22:07.406Z - info: Installing Vagrant plugin vagrant-hostsupdater
> 2014-08-08T03:22:21.897Z - info: Wrote configuration file.
> 2014-08-08T03:22:21.928Z - info: Executing box spinup.
> 2014-08-08T03:22:21.958Z - info: Starting spinup attempt 0
> 2014-08-08T03:22:22.432Z - warn: Spinup attempt 0 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
> to set one up in this directory, or change to a directory with a
> Vagrantfile and try again.
> 
> 2014-08-08T03:22:22.934Z - info: Starting spinup attempt 1
> 2014-08-08T03:22:23.418Z - warn: Spinup attempt 1 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
> to set one up in this directory, or change to a directory with a
> Vagrantfile and try again.
> 
> 2014-08-08T03:22:23.923Z - info: Starting spinup attempt 2
> 2014-08-08T03:22:24.401Z - warn: Spinup attempt 2 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
> to set one up in this directory, or change to a directory with a
> Vagrantfile and try again.
> 
> 2014-08-08T03:22:24.871Z - error: Error during installation routine: An error occurred in an async call.
> cause stack is ...
>   Error: Failed to spin up virtual machine after 3 attempts. Error was: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
> to set one up in this directory, or change to a directory with a
> Vagrantfile and try again.
> 
> ```
> at eval (/private/var/folders/xd/cj9dhbfd2z5cqwdfvly6qyzm0000gn/T/.org.chromium.Chromium.KYAsdL/kalabox/installer/install-utils.js:359:22)
> at ChildProcess.exithandler (child_process.js:665:7)
> at ChildProcess.EventEmitter.emit (events.js:101:17)
> at maybeClose (child_process.js:773:16)
> at Socket.eval (child_process.js:994:11)
> at Socket.EventEmitter.emit (events.js:98:17)
> at Pipe.eval [as close] (net.js:459:12)
> ```
> 
> async call history is ...
>  [ { function: 'install16',
>     location: '/private/var/folders/xd/cj9dhbfd2z5cqwdfvly6qyzm0000gn/T/.org.chromium.Chromium.KYAsdL/kalabox/installer/installer.js:484:33',
>     mapping: { description: 'tail' } } ]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalaboxv1/issues/116#issuecomment-51559613.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by pi-ron** [comment]
The log also says `Kalabox Version: 1.0-beta7` but I've definitely downloaded the latest version `kalabox-1.0-beta8.dmg`
