### ISSUE TITLE
Install for multiple users of same mac

### ISSUE THREAD

**Issue by ModulesUnraveled** [kalamuna/kalaboxv1#123]
I got the following error when trying to install Kalabox for another user on the same mac.
### Kalabox Log

2014-08-27T19:52:17.360Z - info: Box initialized.
2014-08-27T19:52:17.361Z - info: Kalabox Version: 1.0-beta7
2014-08-27T19:52:17.362Z - info: Mac OS Version: 10.9.4

2014-08-27T19:52:17.362Z - info: VirtualBox Version: 4.3.6r91406

2014-08-27T19:52:17.362Z - info: Vagrant Version: Vagrant 1.4.3

2014-08-27T19:53:12.556Z - info: Box initialized.
2014-08-27T19:53:12.559Z - info: Kalabox Version: 1.0-beta7
2014-08-27T19:53:12.559Z - info: Mac OS Version: 10.9.4

2014-08-27T19:53:12.559Z - info: VirtualBox Version: 4.3.6r91406

2014-08-27T19:53:12.559Z - info: Vagrant Version: Vagrant 1.4.3

2014-08-27T19:53:35.058Z - info: Existing VirtualBox installation, version 4.3.6
2014-08-27T19:53:35.060Z - info: Existing Vagrant installation, version 1.4.3
2014-08-27T19:53:37.112Z - info: Existing VirtualBox installation, version 4.3.6
2014-08-27T19:53:37.112Z - info: Existing Vagrant installation, version 1.4.3
2014-08-27T20:03:49.144Z - info: Box image downloaded.
2014-08-27T20:03:50.228Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-08-27T20:03:51.326Z - info: Kalastack downloaded
2014-08-27T20:03:51.327Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-08-27T20:04:03.446Z - info: Adding base box image to Vagrant.
2014-08-27T20:04:07.483Z - info: Wrote configuration file.
2014-08-27T20:04:07.579Z - info: Executing box spinup.
2014-08-27T20:04:07.628Z - info: Starting spinup attempt 0
2014-08-27T20:04:26.904Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  undefined
async call history is ...
 [ { function: 'install6',
    location: '/private/var/folders/00/dzx9bwsx7gz9h_pf4xlxn_8m0000gp/T/.org.chromium.Chromium.lz10Jx/kalabox/installer/installer.js:390:58',
    mapping: { description: 'tail' } } ]
##

**Comment by ModulesUnraveled** [comment]
Just thought I'd follow up with this error. I was able to successfully use Kalabox when logged in as the second user, but when I clicked the "Stop" button, this error was displayed.

### Kalabox Log

2014-08-27T19:52:17.360Z - info: Box initialized.
2014-08-27T19:52:17.361Z - info: Kalabox Version: 1.0-beta7
2014-08-27T19:52:17.362Z - info: Mac OS Version: 10.9.4

2014-08-27T19:52:17.362Z - info: VirtualBox Version: 4.3.6r91406

2014-08-27T19:52:17.362Z - info: Vagrant Version: Vagrant 1.4.3

2014-08-27T19:53:12.556Z - info: Box initialized.
2014-08-27T19:53:12.559Z - info: Kalabox Version: 1.0-beta7
2014-08-27T19:53:12.559Z - info: Mac OS Version: 10.9.4

2014-08-27T19:53:12.559Z - info: VirtualBox Version: 4.3.6r91406

2014-08-27T19:53:12.559Z - info: Vagrant Version: Vagrant 1.4.3

2014-08-27T19:53:35.058Z - info: Existing VirtualBox installation, version 4.3.6
2014-08-27T19:53:35.060Z - info: Existing Vagrant installation, version 1.4.3
2014-08-27T19:53:37.112Z - info: Existing VirtualBox installation, version 4.3.6
2014-08-27T19:53:37.112Z - info: Existing Vagrant installation, version 1.4.3
2014-08-27T20:03:49.144Z - info: Box image downloaded.
2014-08-27T20:03:50.228Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-08-27T20:03:51.326Z - info: Kalastack downloaded
2014-08-27T20:03:51.327Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-08-27T20:04:03.446Z - info: Adding base box image to Vagrant.
2014-08-27T20:04:07.483Z - info: Wrote configuration file.
2014-08-27T20:04:07.579Z - info: Executing box spinup.
2014-08-27T20:04:07.628Z - info: Starting spinup attempt 0
2014-08-27T20:04:26.904Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  undefined
async call history is ...
 [ { function: 'install6',
    location: '/private/var/folders/00/dzx9bwsx7gz9h_pf4xlxn_8m0000gp/T/.org.chromium.Chromium.lz10Jx/kalabox/installer/installer.js:390:58',
    mapping: { description: 'tail' } } ]
2014-08-27T20:05:05.187Z - info: Box initialized.
2014-08-27T20:05:05.188Z - info: Kalabox Version: 1.0-beta7
2014-08-27T20:05:05.188Z - info: Mac OS Version: 10.9.4

2014-08-27T20:05:05.188Z - info: VirtualBox Version: 4.3.6r91406

2014-08-27T20:05:05.188Z - info: Vagrant Version: Vagrant 1.4.3

2014-08-27T20:05:06.079Z - warn: Error retrieving sites list: Error: getaddrinfo ENOTFOUND
2014-08-27T20:05:26.797Z - warn: Box has no Internet connection.
2014-08-27T20:06:02.618Z - info: Box initialized.
2014-08-27T20:06:02.619Z - info: Kalabox Version: 1.0-beta7
2014-08-27T20:06:02.619Z - info: Mac OS Version: 10.9.4

2014-08-27T20:06:02.619Z - info: VirtualBox Version: 4.3.6r91406

2014-08-27T20:06:02.619Z - info: Vagrant Version: Vagrant 1.4.3

2014-08-27T20:06:03.403Z - warn: Error retrieving sites list: Error: getaddrinfo ENOTFOUND
2014-08-27T20:06:23.544Z - info: Box initialized.
2014-08-27T20:06:23.545Z - info: Kalabox Version: 1.0-beta7
2014-08-27T20:06:23.546Z - info: Mac OS Version: 10.9.4

2014-08-27T20:06:23.546Z - info: VirtualBox Version: 4.3.6r91406

2014-08-27T20:06:23.546Z - info: Vagrant Version: Vagrant 1.4.3

2014-08-27T23:21:56.458Z - error: An error occurred in an async call.
cause stack is ...
  Error: Command failed: No user UUID found. Please authenticate first using 'drush pauth'        [error]
Connection to 127.0.0.1 closed by remote host.

```
at ChildProcess.exithandler (child_process.js:661:12)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Socket.eval (child_process.js:994:11)
at Socket.EventEmitter.emit (events.js:98:17)
at Pipe.eval [as close] (net.js:459:12)
```

async call history is ...
 [ { function: 'startBox4',
    location: '/private/var/folders/00/dzx9bwsx7gz9h_pf4xlxn_8m0000gp/T/.org.chromium.Chromium.jHcJaN/kalabox/box.js:168:108',
    mapping: { description: 'tail' } } ]

**Comment by pirog** [comment]
if you ssh into the box and then `drush pauth` does it resolve the error?

**Comment by ModulesUnraveled** [comment]
Not sure. I just ran it for the original user. It logged into terminus just fine. I'll post back if I notice anything else.
