### ISSUE TITLE
Uh oh... (after starting up for the first time in awhile)

### ISSUE THREAD

**Issue by davidneedham** [kalamuna/kalaboxv1#125]
Here is what I was told to paste. It's probably been a month or two since I've used Kalabox, and was surprised that it had to re-download stuff.
### Kalabox Log

2014-06-10T15:37:27.267Z - info: Box initialized.
2014-06-10T15:37:27.269Z - info: Kalabox Version: 1.0-beta5
2014-06-10T15:37:27.269Z - info: Mac OS Version: 10.8.5

2014-06-10T15:37:27.269Z - info: VirtualBox Version: 4.2.18r88780

2014-06-10T15:37:27.269Z - info: Vagrant Version: Vagrant 1.4.3

2014-06-12T22:26:18.031Z - info: Box initialized.
2014-06-12T22:26:18.032Z - info: Kalabox Version: 1.0-beta5
2014-06-12T22:26:18.032Z - info: Mac OS Version: 10.8.5

2014-06-12T22:26:18.032Z - info: VirtualBox Version: 4.2.18r88780

2014-06-12T22:26:18.033Z - info: Vagrant Version: Vagrant 1.4.3

2014-06-12T22:26:21.585Z - info: User accepted license.
2014-06-12T22:26:28.990Z - info: Existing VirtualBox installation, version 4.2.18
2014-06-12T22:26:28.991Z - info: Existing Vagrant installation, version 1.4.3
2014-06-12T22:26:28.991Z - info: VirtualBox not installed or wrong version. Installing.
2014-06-12T22:26:37.001Z - info: User granted permission to install VirtualBox
2014-06-12T22:55:17.486Z - info: Successfully downloaded VirtualBox DMG.
2014-06-12T22:55:31.321Z - info: Successfully mounted VirtualBox DMG.
2014-06-12T22:55:55.698Z - info: VirtualBox installation complete.
2014-06-12T22:55:55.896Z - info: Successfully ejected VirtualBox DMG.
2014-06-13T00:29:15.896Z - info: Box initialized.
2014-06-13T00:29:15.898Z - info: Kalabox Version: 1.0-beta5
2014-06-13T00:29:15.898Z - info: Mac OS Version: 10.8.5

2014-06-13T00:29:15.898Z - info: VirtualBox Version: 4.3.6r91406

2014-06-13T00:29:15.898Z - info: Vagrant Version: Vagrant 1.4.3

2014-06-13T00:29:20.389Z - info: User accepted license.
2014-06-13T00:29:21.133Z - info: Existing VirtualBox installation, version 4.3.6
2014-06-13T00:29:21.134Z - info: Existing Vagrant installation, version 1.4.3
2014-06-19T19:00:16.533Z - info: Box initialized.
2014-06-19T19:00:16.535Z - info: Kalabox Version: 1.0-beta5
2014-06-19T19:00:16.535Z - info: Mac OS Version: 10.8.5

2014-06-19T19:00:16.535Z - info: VirtualBox Version: 4.3.6r91406

2014-06-19T19:00:16.535Z - info: Vagrant Version: Vagrant 1.4.3

2014-06-19T19:00:34.439Z - info: User accepted license.
2014-06-19T19:00:35.200Z - info: Existing VirtualBox installation, version 4.3.6
2014-06-19T19:00:35.201Z - info: Existing Vagrant installation, version 1.4.3
2014-06-19T19:04:12.226Z - info: Box initialized.
2014-06-19T19:04:12.229Z - info: Kalabox Version: 1.0-beta5
2014-06-19T19:04:12.229Z - info: Mac OS Version: 10.8.5

2014-06-19T19:04:12.229Z - info: VirtualBox Version: 4.3.6r91406

2014-06-19T19:04:12.229Z - info: Vagrant Version: Vagrant 1.4.3

2014-06-19T19:04:14.950Z - info: User accepted license.
2014-06-19T19:04:15.067Z - info: Existing VirtualBox installation, version 4.3.6
2014-06-19T19:04:15.068Z - info: Existing Vagrant installation, version 1.4.3
2014-06-19T19:14:24.806Z - info: Box image downloaded.
2014-06-19T19:14:25.739Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-06-19T19:14:26.779Z - info: Kalastack downloaded
2014-06-19T19:14:26.780Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-06-19T19:14:41.376Z - info: Adding base box image to Vagrant.
2014-06-19T19:15:33.879Z - info: Wrote configuration file.
2014-06-19T19:15:33.968Z - info: Executing box spinup.
2014-06-19T19:15:34.038Z - info: Starting spinup attempt 0
2014-06-19T19:30:06.625Z - info: Box initialized.
2014-06-19T19:30:06.625Z - info: Kalabox Version: 1.0-beta5
2014-06-19T19:30:06.625Z - info: Mac OS Version: 10.8.5

2014-06-19T19:30:06.625Z - info: VirtualBox Version: 4.3.6r91406

2014-06-19T19:30:06.625Z - info: Vagrant Version: Vagrant 1.4.3

2014-06-19T19:30:06.626Z - info: Installation completed successfully.
2014-06-19T21:01:32.193Z - info: Box initialized.
2014-06-19T21:01:32.195Z - info: Kalabox Version: 1.0-beta5
2014-06-19T21:01:32.195Z - info: Mac OS Version: 10.8.5

2014-06-19T21:01:32.195Z - info: VirtualBox Version: 4.3.6r91406

2014-06-19T21:01:32.195Z - info: Vagrant Version: Vagrant 1.4.3

2014-07-02T22:09:21.252Z - info: Box initialized.
2014-07-02T22:09:21.254Z - info: Kalabox Version: 1.0-beta6
2014-07-02T22:09:21.254Z - info: Mac OS Version: 10.8.5

2014-07-02T22:09:21.254Z - info: VirtualBox Version: 4.3.6r91406

2014-07-02T22:09:21.254Z - info: Vagrant Version: Vagrant 1.4.3

2014-09-10T16:07:41.027Z - info: Box initialized.
2014-09-10T16:07:41.029Z - info: Kalabox Version: 1.0-beta6
2014-09-10T16:07:41.029Z - info: Mac OS Version: 10.9.4

2014-09-10T16:07:41.029Z - info: VirtualBox Version: 4.3.6r91406

2014-09-10T16:07:41.030Z - info: Vagrant Version: false
2014-09-10T16:07:43.774Z - info: Existing VirtualBox installation, version 4.3.6
2014-09-10T16:07:43.776Z - info: Vagrant not installed or wrong version. Installing.
2014-09-10T16:07:43.777Z - info: User granted permission to install Vagrant
2014-09-10T16:08:13.990Z - info: Successfully downloaded Vagrant DMG.
2014-09-10T16:08:20.200Z - info: Successfully mounted Vagrant DMG.
2014-09-10T16:08:31.364Z - info: Vagrant installation complete.
2014-09-10T16:08:31.595Z - info: Successfully ejected Vagrant DMG.
2014-09-10T16:08:31.613Z - info: Kalabox image already downloaded.
2014-09-10T16:08:31.614Z - info: Box image downloaded.
2014-09-10T16:08:31.615Z - info: Kalastack already downloaded
2014-09-10T16:08:31.617Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-09-10T16:08:33.566Z - info: Kalastack downloaded
2014-09-10T16:08:33.567Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-09-10T16:08:47.234Z - info: Adding base box image to Vagrant.
2014-09-10T16:09:45.670Z - info: Wrote configuration file.
2014-09-10T16:09:45.754Z - info: Executing box spinup.
2014-09-10T16:09:45.820Z - info: Starting spinup attempt 0
2014-09-10T16:09:47.436Z - warn: Spinup attempt 0 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-09-10T16:09:48.303Z - info: Starting spinup attempt 1
2014-09-10T16:09:49.086Z - warn: Spinup attempt 1 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-09-10T16:09:49.946Z - info: Starting spinup attempt 2
2014-09-10T16:09:50.695Z - warn: Spinup attempt 2 failed with error: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

2014-09-10T16:09:51.495Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Failed to spin up virtual machine after 3 attempts. Error was: Command failed: A Vagrant environment is required to run this command. Run `vagrant init`
to set one up in this directory, or change to a directory with a
Vagrantfile and try again.

```
at eval (/private/var/folders/9s/pxjlyzy17x1_x9b0mm4k2chr0000gn/T/.org.chromium.Chromium.nLDCZb/kalabox/installer/install-utils.js:359:22)
at ChildProcess.exithandler (child_process.js:665:7)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Socket.eval (child_process.js:994:11)
at Socket.EventEmitter.emit (events.js:98:17)
at Pipe.eval [as close] (net.js:459:12)
```

async call history is ...
 [ { function: 'install16',
    location: '/private/var/folders/9s/pxjlyzy17x1_x9b0mm4k2chr0000gn/T/.org.chromium.Chromium.nLDCZb/kalabox/installer/installer.js:479:33',
    mapping: { description: 'tail' } } ]
##

**Comment by davidneedham** [comment]
This is still an issue. I tried removing Kalabox completely and reinstalling from scratch. I got this updated error:

### Kalabox Log

2014-11-18T16:27:01.851Z - info: Box initialized.
2014-11-18T16:27:01.853Z - info: Kalabox Version: 1.0-beta7
2014-11-18T16:27:01.854Z - info: Mac OS Version: 10.9.5

2014-11-18T16:27:01.854Z - info: VirtualBox Version: 4.3.6r91406

2014-11-18T16:27:01.854Z - info: Vagrant Version: Vagrant 1.4.3

2014-11-18T16:27:04.660Z - info: Existing VirtualBox installation, version 4.3.6
2014-11-18T16:27:04.661Z - info: Existing Vagrant installation, version 1.4.3
2014-11-18T16:31:44.414Z - info: Box image downloaded.
2014-11-18T16:31:45.256Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-11-18T16:31:46.398Z - info: Kalastack downloaded
2014-11-18T16:31:46.399Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-11-18T16:31:57.558Z - info: Wrote configuration file.
2014-11-18T16:31:57.608Z - info: Executing box spinup.
2014-11-18T16:31:57.648Z - info: Starting spinup attempt 0
2014-11-18T16:32:21.796Z - warn: Spinup attempt 0 failed with error: Command failed: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterface, interface IHostNetworkInterface
VBoxManage: error: Context: "int handleCreate(HandlerArg_, int, int_)" at line 66 of file VBoxManageHostonly.cpp

2014-11-18T16:32:25.745Z - info: Starting spinup attempt 1
2014-11-18T16:32:40.943Z - warn: Spinup attempt 1 failed with error: Command failed: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterface, interface IHostNetworkInterface
VBoxManage: error: Context: "int handleCreate(HandlerArg_, int, int_)" at line 66 of file VBoxManageHostonly.cpp

2014-11-18T16:32:44.769Z - info: Starting spinup attempt 2
2014-11-18T16:33:00.694Z - warn: Spinup attempt 2 failed with error: Command failed: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterface, interface IHostNetworkInterface
VBoxManage: error: Context: "int handleCreate(HandlerArg_, int, int_)" at line 66 of file VBoxManageHostonly.cpp

2014-11-18T16:33:05.800Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Failed to spin up virtual machine after 3 attempts. Error was: Command failed: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterface, interface IHostNetworkInterface
VBoxManage: error: Context: "int handleCreate(HandlerArg_, int, int_)" at line 66 of file VBoxManageHostonly.cpp

```
at eval (/private/var/folders/9s/pxjlyzy17x1_x9b0mm4k2chr0000gn/T/.org.chromium.Chromium.c6W8yw/kalabox/installer/install-utils.js:359:22)
at ChildProcess.exithandler (child_process.js:659:7)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Process.ChildProcess._handle.onexit (child_process.js:840:5)
```

async call history is ...
 [ { function: 'install16',
    location: '/private/var/folders/9s/pxjlyzy17x1_x9b0mm4k2chr0000gn/T/.org.chromium.Chromium.c6W8yw/kalabox/installer/installer.js:484:33',
    mapping: { description: 'tail' } } ]
