### ISSUE TITLE
On Installation: Uh oh... It seems we've run into an unexpected error.

### ISSUE THREAD

**Issue by robearmingyo** [kalamuna/kalaboxv1#126]
### Kalabox Log

2014-09-15T03:45:41.849Z - info: Box initialized.
2014-09-15T03:45:41.850Z - info: Kalabox Version: 1.0-beta7
2014-09-15T03:45:41.851Z - info: Mac OS Version: 10.9.4

2014-09-15T03:45:41.851Z - info: VirtualBox Version: false
2014-09-15T03:45:41.851Z - info: Vagrant Version: false
2014-09-15T03:45:47.276Z - info: VirtualBox not installed or wrong version. Installing.
2014-09-15T03:45:47.277Z - info: User granted permission to install VirtualBox
2014-09-15T03:52:52.082Z - info: Successfully downloaded VirtualBox DMG.
2014-09-15T03:53:14.603Z - info: Successfully mounted VirtualBox DMG.
2014-09-15T03:55:00.781Z - info: VirtualBox installation complete.
2014-09-15T03:55:01.177Z - info: Successfully ejected VirtualBox DMG.
2014-09-15T03:55:01.178Z - info: Vagrant not installed or wrong version. Installing.
2014-09-15T03:55:01.178Z - info: User granted permission to install Vagrant
2014-09-15T03:56:39.156Z - info: Successfully downloaded Vagrant DMG.
2014-09-15T03:56:43.123Z - info: Successfully mounted Vagrant DMG.
2014-09-15T03:56:58.333Z - info: Vagrant installation complete.
2014-09-15T03:56:58.505Z - info: Successfully ejected Vagrant DMG.
2014-09-15T03:56:58.514Z - info: Kalabox image already downloaded.
2014-09-15T03:56:58.514Z - info: Box image downloaded.
2014-09-15T03:57:01.159Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-09-15T03:57:04.586Z - info: Kalastack downloaded
2014-09-15T03:57:04.586Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-09-15T03:57:26.100Z - info: Adding base box image to Vagrant.
2014-09-15T03:57:46.513Z - info: Wrote configuration file.
2014-09-15T03:57:46.773Z - info: Executing box spinup.
2014-09-15T03:57:46.817Z - info: Starting spinup attempt 0
2014-09-15T03:59:56.190Z - warn: Spinup attempt 0 failed with error: Command failed: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'nolock' 1.3.3.1:'/Users/robert/kalabox/www' /var/www

Stdout from the command:

Stderr from the command:

stdin: is not a tty
mount.nfs: access denied by server while mounting 1.3.3.1:/Users/robert/kalabox/www

2014-09-15T04:00:02.194Z - info: Starting spinup attempt 1
2014-09-15T04:01:58.948Z - warn: Spinup attempt 1 failed with error: Command failed: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'nolock' 1.3.3.1:'/Users/robert/kalabox/www' /var/www

Stdout from the command:

Stderr from the command:

stdin: is not a tty
mount.nfs: access denied by server while mounting 1.3.3.1:/Users/robert/kalabox/www

2014-09-15T04:02:02.964Z - info: Starting spinup attempt 2
2014-09-15T04:03:54.251Z - warn: Spinup attempt 2 failed with error: Command failed: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'nolock' 1.3.3.1:'/Users/robert/kalabox/www' /var/www

Stdout from the command:

Stderr from the command:

stdin: is not a tty
mount.nfs: access denied by server while mounting 1.3.3.1:/Users/robert/kalabox/www

2014-09-15T04:03:58.329Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Failed to spin up virtual machine after 3 attempts. Error was: Command failed: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'nolock' 1.3.3.1:'/Users/robert/kalabox/www' /var/www

Stdout from the command:

Stderr from the command:

stdin: is not a tty
mount.nfs: access denied by server while mounting 1.3.3.1:/Users/robert/kalabox/www

```
at eval (/private/var/folders/gp/ctc310lh8vl4lp0059bj6_h00000gn/T/.org.chromium.Chromium.8IE3fH/kalabox/installer/install-utils.js:359:22)
at ChildProcess.exithandler (child_process.js:659:7)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Socket.eval (child_process.js:994:11)
at Socket.EventEmitter.emit (events.js:98:17)
at Pipe.eval [as close] (net.js:459:12)
```

async call history is ...
 [ { function: 'install16',
    location: '/private/var/folders/gp/ctc310lh8vl4lp0059bj6_h00000gn/T/.org.chromium.Chromium.8IE3fH/kalabox/installer/installer.js:484:33',
    mapping: { description: 'tail' } } ]
##

**Comment by bgonz** [comment]
I got this same Error
