### ISSUE TITLE
Having problems installing - error message below

### ISSUE THREAD

**Issue by bodhiprice** [kalamuna/kalaboxv1#128]
### Kalabox Log

2014-09-25T15:15:09.048Z - info: Box initialized.
2014-09-25T15:15:09.049Z - info: Kalabox Version: 1.0-beta7
2014-09-25T15:15:09.049Z - info: Mac OS Version: 10.9.5

2014-09-25T15:15:09.049Z - info: VirtualBox Version: 4.3.8r92456

2014-09-25T15:15:09.049Z - info: Vagrant Version: Vagrant 1.4.3

2014-09-25T15:15:12.138Z - info: Existing VirtualBox installation, version 4.3.8
2014-09-25T15:15:12.138Z - info: Existing Vagrant installation, version 1.4.3
2014-09-25T15:16:41.022Z - info: Box image downloaded.
2014-09-25T15:16:42.106Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-09-25T15:16:42.733Z - info: Kalastack downloaded
2014-09-25T15:16:42.734Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-09-25T15:16:50.605Z - info: Adding base box image to Vagrant.
2014-09-25T15:16:52.029Z - info: Wrote configuration file.
2014-09-25T15:16:52.079Z - info: Executing box spinup.
2014-09-25T15:16:52.106Z - info: Starting spinup attempt 0
2014-09-25T15:17:00.082Z - warn: Spinup attempt 0 failed with error: Command failed: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterface, interface IHostNetworkInterface
VBoxManage: error: Context: "int handleCreate(HandlerArg_, int, int_)" at line 66 of file VBoxManageHostonly.cpp

2014-09-25T15:17:02.541Z - info: Starting spinup attempt 1
2014-09-25T15:17:09.850Z - warn: Spinup attempt 1 failed with error: Command failed: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterface, interface IHostNetworkInterface
VBoxManage: error: Context: "int handleCreate(HandlerArg_, int, int_)" at line 66 of file VBoxManageHostonly.cpp

2014-09-25T15:17:12.165Z - info: Starting spinup attempt 2
2014-09-25T15:17:19.200Z - warn: Spinup attempt 2 failed with error: Command failed: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterface, interface IHostNetworkInterface
VBoxManage: error: Context: "int handleCreate(HandlerArg_, int, int_)" at line 66 of file VBoxManageHostonly.cpp

2014-09-25T15:17:21.440Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Failed to spin up virtual machine after 3 attempts. Error was: Command failed: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterface, interface IHostNetworkInterface
VBoxManage: error: Context: "int handleCreate(HandlerArg_, int, int_)" at line 66 of file VBoxManageHostonly.cpp

```
at eval (/private/var/folders/dl/39p2hkkd1y7cvwqz7wqcy56m0000gp/T/.org.chromium.Chromium.fpaWLR/kalabox/installer/install-utils.js:359:22)
at ChildProcess.exithandler (child_process.js:659:7)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Socket.eval (child_process.js:994:11)
at Socket.EventEmitter.emit (events.js:98:17)
at Pipe.eval [as close] (net.js:459:12)
```

async call history is ...
 [ { function: 'install16',
    location: '/private/var/folders/dl/39p2hkkd1y7cvwqz7wqcy56m0000gp/T/.org.chromium.Chromium.fpaWLR/kalabox/installer/installer.js:484:33',
    mapping: { description: 'tail' } } ]

**Comment by bodhiprice** [comment]
Fixed! For any who see this later - I had to uninstall both Vagrant and VirtualBox - including the hidden files/folders in my User directory - to get the install to work correctly.
