### ISSUE TITLE
Uh oh... when installing beta8 on Mac OS 10.9.4.

### ISSUE THREAD

**Issue by fureigh** [kalamuna/kalaboxv1#134]
```
### Kalabox Log ###

2014-11-21T07:09:57.718Z - info: Box initialized.
2014-11-21T07:09:57.719Z - info: Kalabox Version: 1.0-beta7
2014-11-21T07:09:57.719Z - info: Mac OS Version: 10.9.4

2014-11-21T07:09:57.719Z - info: VirtualBox Version: false
2014-11-21T07:09:57.719Z - info: Vagrant Version: false
2014-11-21T07:10:15.173Z - info: VirtualBox not installed or wrong version. Installing.
2014-11-21T07:10:15.179Z - info: User granted permission to install VirtualBox
2014-11-21T07:12:33.480Z - info: Successfully downloaded VirtualBox DMG.
2014-11-21T07:12:50.345Z - info: Successfully mounted VirtualBox DMG.
2014-11-21T07:13:15.271Z - info: VirtualBox installation complete.
2014-11-21T07:13:15.649Z - info: Successfully ejected VirtualBox DMG.
2014-11-21T07:13:15.649Z - info: Vagrant not installed or wrong version. Installing.
2014-11-21T07:13:15.650Z - info: User granted permission to install Vagrant
2014-11-21T07:13:41.531Z - info: Successfully downloaded Vagrant DMG.
2014-11-21T07:13:47.135Z - info: Successfully mounted Vagrant DMG.
2014-11-21T07:13:56.210Z - info: Vagrant installation complete.
2014-11-21T07:13:56.594Z - info: Successfully ejected Vagrant DMG.
2014-11-21T07:25:09.065Z - info: Box image downloaded.
2014-11-21T07:25:10.298Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-11-21T07:25:11.998Z - info: Kalastack downloaded
2014-11-21T07:25:11.998Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-11-21T07:25:23.089Z - info: Adding base box image to Vagrant.
2014-11-21T07:25:25.559Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Command failed: The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

x box-disk1.vmdk: Truncated tar archive
bsdtar: Error exit delayed from previous errors.

    at ChildProcess.exithandler (child_process.js:661:12)
    at ChildProcess.EventEmitter.emit (events.js:101:17)
    at maybeClose (child_process.js:773:16)
    at Process.ChildProcess._handle.onexit (child_process.js:840:5)
async call history is ...
 [ { function: 'install13',
    location: '/private/var/folders/8m/k82yp3kd1ynfpgnjx04j2gdw0000gn/T/.org.chromium.Chromium.5E441d/kalabox/installer/installer.js:463:109',
    mapping: { description: 'tail' } } ]
```
##

**Comment by fureigh** [comment]
The same error occurred again after I ran the uninstall tool and selected option 1. As in another user's bug report, don't be fooled by the log above: I'm definitely using beta8 and not beta7.

**Comment by pirog** [comment]
Have you tried deleting the previously corrupted box file?

On Thursday, November 20, 2014, Fureigh notifications@github.com wrote:

> The same error occurred again after I ran the uninstall tool and selected
> option 1. As in another user's bug report, don't be fooled by the log
> above: I'm definitely using beta8 and not beta7.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalaboxv1/issues/134#issuecomment-63934090.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com
