### ISSUE TITLE
Pantheon Download From Latest Backup feature returning 403 No realm detected error

### ISSUE THREAD

**Issue by grego3** [kalamuna/kalaboxv1#137]
I recently got added to a project on Pantheon. When I refresh the "My Sites" screen in Kalabox, the new site shows up, but I can't download it. I tried all three methods of downloading the site (Download from latest backup, Create new backup and download, and choose from a list of backups). When I try to choose from a list of backups, no backups show.

I checked my logs and I'm getting this 403 "No realm detected" error.

2014-12-23T17:30:03.209Z - info: Kalabox Version: 1.0-beta7
2014-12-23T17:30:03.209Z - info: Mac OS Version: 10.9.5

2014-12-23T17:30:03.209Z - info: VirtualBox Version: 4.3.6r91406

2014-12-23T17:30:03.209Z - info: Vagrant Version: Vagrant 1.4.3

2014-12-23T17:31:27.433Z - warn: An error occurred in an async call.
cause stack is ...
  Error: Command failed: Request failed: 403 "No realm detected."                                [failed]
Could not clone code from the remote repository. Check that your SSH     [error]
key is loaded and the codeserver is reachable.

```
at ChildProcess.exithandler (child_process.js:661:12)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Socket.eval (child_process.js:994:11)
at Socket.EventEmitter.emit (events.js:98:17)
at Pipe.eval [as close] (net.js:459:12)
```

async call history is ...
 [ { function: 'buildSite2',
    location: '/private/var/folders/h8/3kjvq__j7tq2lb7c56sk4l5r0000gq/T/.org.chromium.Chromium.OGlnMQ/kalabox/vm/sites-manager.js:106:75',
    mapping: { description: 'tail' } } ]
##

**Comment by pirog** [comment]
I'm not positive but i think the 403 "no realm" issue is well documented in
the issues with some actionable resolution issues.

On Tue, Dec 23, 2014 at 9:39 AM, grego3 notifications@github.com wrote:

> I recently got added to a project on Pantheon. When I refresh the "My
> Sites" screen in Kalabox, the new site shows up, but I can't download it. I
> tried all three methods of downloading the site (Download from latest
> backup, Create new backup and download, and choose from a list of backups).
> When I try to choose from a list of backups, no backups show.
> 
> I checked my logs and I'm getting this 403 "No realm detected" error.
> 
> 2014-12-23T17:30:03.209Z - info: Kalabox Version: 1.0-beta7
> 2014-12-23T17:30:03.209Z - info: Mac OS Version: 10.9.5
> 
> 2014-12-23T17:30:03.209Z - info: VirtualBox Version: 4.3.6r91406
> 
> 2014-12-23T17:30:03.209Z - info: Vagrant Version: Vagrant 1.4.3
> 
> 2014-12-23T17:31:27.433Z - warn: An error occurred in an async call.
> cause stack is ...
> Error: Command failed: Request failed: 403 "No realm detected." [failed]
> Could not clone code from the remote repository. Check that your SSH
> [error]
> key is loaded and the codeserver is reachable.
> 
> at ChildProcess.exithandler (child_process.js:661:12)
> at ChildProcess.EventEmitter.emit (events.js:101:17)
> at maybeClose (child_process.js:773:16)
> at Socket.eval (child_process.js:994:11)
> at Socket.EventEmitter.emit (events.js:98:17)
> at Pipe.eval [as close](net.js:459:12)
> 
> async call history is ...
> [ { function: 'buildSite2',
> location:
> '/private/var/folders/h8/3kjvq__j7tq2lb7c56sk4l5r0000gq/T/.org.chromium.Chromium.OGlnMQ/kalabox/vm/sites-manager.js:106:75',
> mapping: { description: 'tail' } } ]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalaboxv1/issues/137.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by grego3** [comment]
Uninstalling Kalabox and installing the latest version seems to have fixed the issue.
