### ISSUE TITLE
Failed install:    Error: Command failed: /bin/sh: vagrant: command not found

### ISSUE THREAD

**Issue by nepennington** [kalamuna/kalaboxv1#154]
2015-06-19T22:52:28.370Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Command failed: /bin/sh: vagrant: command not found

```
at ChildProcess.exithandler (child_process.js:661:12)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Socket.eval (child_process.js:994:11)
at Socket.EventEmitter.emit (events.js:98:17)
at Pipe.eval [as close] (net.js:459:12)
```

async call history is ...
 [ { function: 'eval',
    location: '/private/var/folders/7n/z7l4f7_54394dbdgrg_bqpfw0000gq/T/.org.chromium.Chromium.L6Apgf/kalabox/installer/installer.js:425:85',
    mapping: { description: 'tail' } } ]

**Comment by nepennington** [comment]
https://github.com/mitchellh/vagrant-installers/issues/54

timsutton commented 10 days ago
On OS X 10.11, installing the vagrant pkg will result in success, however a new security feature of OS X prevents user modification to certain system folders, including /usr/bin (it can be overridden, but non-trivially). A snippet from the install log where a symlink attempts to be created in /usr/bin:

Jun  9 12:48:37 test-mini installd[375]: ./postinstall: ln: /usr/bin/vagrant: Operation not permitted
Tools and Puppet and Chef have similar issues, for example:

https://tickets.puppetlabs.com/browse/PUP-4714

/usr/local/bin is in the default PATH so it seems natural that the vagrant symlink could go there. Alternatively there's also the option of dropping additional paths in /etc/paths.d, but I'm not sure which shells beyond the stock Bash will automatically include those.
