### ISSUE TITLE
Kalabox not working after El Capitan update in Mac

### ISSUE THREAD

**Issue by nbhatia3** [kalamuna/kalaboxv1#159]
### Kalabox Log

2016-01-28T20:26:06.555Z - info: Box initialized.
2016-01-28T20:26:06.556Z - info: Kalabox Version: 1.0-beta7
2016-01-28T20:26:06.557Z - info: Mac OS Version: 10.11.3

2016-01-28T20:26:06.557Z - info: VirtualBox Version: false
2016-01-28T20:26:06.557Z - info: Vagrant Version: false
2016-01-28T20:26:11.847Z - info: VirtualBox not installed or wrong version. Installing.
2016-01-28T20:26:11.848Z - info: User granted permission to install VirtualBox
2016-01-28T20:28:32.227Z - info: Successfully downloaded VirtualBox DMG.
2016-01-28T20:28:45.120Z - info: Successfully mounted VirtualBox DMG.
2016-01-28T20:29:05.096Z - info: VirtualBox installation complete.
2016-01-28T20:29:16.291Z - info: Successfully ejected VirtualBox DMG.
2016-01-28T20:29:16.369Z - info: Vagrant not installed or wrong version. Installing.
2016-01-28T20:29:16.369Z - info: User granted permission to install Vagrant
2016-01-28T20:29:21.399Z - info: Successfully downloaded Vagrant DMG.
2016-01-28T20:29:26.308Z - info: Successfully mounted Vagrant DMG.
2016-01-28T20:29:45.951Z - info: Vagrant installation complete.
2016-01-28T20:29:46.044Z - info: Successfully ejected Vagrant DMG.
2016-01-28T20:29:46.072Z - info: Kalabox image already downloaded.
2016-01-28T20:29:46.072Z - info: Box image downloaded.
2016-01-28T20:29:46.696Z - info: Installing Vagrant plugin vagrant-hostsupdater
2016-01-28T20:29:51.282Z - info: Kalastack downloaded
2016-01-28T20:29:51.283Z - info: Installing Vagrant plugin vagrant-hostsupdater
2016-01-28T20:30:00.270Z - info: Adding base box image to Vagrant.
2016-01-28T20:30:26.070Z - info: Wrote configuration file.
2016-01-28T20:30:26.234Z - info: Executing box spinup.
2016-01-28T20:30:26.291Z - info: Starting spinup attempt 0
2016-01-28T20:30:27.560Z - warn: Spinup attempt 0 failed with error: Command failed: The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

2016-01-28T20:30:28.193Z - info: Starting spinup attempt 1
2016-01-28T20:30:28.763Z - warn: Spinup attempt 1 failed with error: Command failed: The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

2016-01-28T20:30:29.350Z - info: Starting spinup attempt 2
2016-01-28T20:30:29.908Z - warn: Spinup attempt 2 failed with error: Command failed: The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

2016-01-28T20:30:30.493Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Failed to spin up virtual machine after 3 attempts. Error was: Command failed: The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

```
at eval (/private/var/folders/pj/15v2ct6x28n9_ql1b1zk9sdr0000gp/T/.org.chromium.Chromium.9HpxZO/kalabox/installer/install-utils.js:359:22)
at ChildProcess.exithandler (child_process.js:665:7)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Socket.eval (child_process.js:994:11)
at Socket.EventEmitter.emit (events.js:98:17)
at Pipe.eval [as close] (net.js:459:12)
```

async call history is ...
 [ { function: 'install16',
    location: '/private/var/folders/pj/15v2ct6x28n9_ql1b1zk9sdr0000gp/T/.org.chromium.Chromium.9HpxZO/kalabox/installer/installer.js:484:33',
    mapping: { description: 'tail' } } ]
2016-01-29T17:01:14.810Z - info: Box initialized.
2016-01-29T17:01:14.811Z - info: Kalabox Version: 1.0-beta7
2016-01-29T17:01:14.812Z - info: Mac OS Version: 10.11.3

2016-01-29T17:01:14.812Z - info: VirtualBox Version: false
2016-01-29T17:01:14.812Z - info: Vagrant Version: Vagrant 1.4.3

2016-01-29T17:01:18.205Z - info: Existing Vagrant installation, version 1.4.3
2016-01-29T17:01:18.206Z - info: VirtualBox not installed or wrong version. Installing.
2016-01-29T17:01:18.206Z - info: User granted permission to install VirtualBox
2016-01-29T17:01:18.216Z - info: File /var/folders/pj/15v2ct6x28n9_ql1b1zk9sdr0000gp/T/virtualbox-macosx-4.3.6.dmg already downloaded.
2016-01-29T17:01:18.216Z - info: Successfully downloaded VirtualBox DMG.
2016-01-29T17:01:20.300Z - info: Successfully mounted VirtualBox DMG.
2016-01-29T17:01:39.008Z - info: VirtualBox installation complete.
2016-01-29T17:01:39.122Z - info: Successfully ejected VirtualBox DMG.
2016-01-29T17:01:39.128Z - info: Kalabox image already downloaded.
2016-01-29T17:01:39.129Z - info: Box image downloaded.
2016-01-29T17:01:39.129Z - info: Kalastack already downloaded
2016-01-29T17:01:39.130Z - info: Installing Vagrant plugin vagrant-hostsupdater
2016-01-29T17:01:40.884Z - info: Kalastack downloaded
2016-01-29T17:01:40.885Z - info: Installing Vagrant plugin vagrant-hostsupdater
2016-01-29T17:01:48.719Z - info: Wrote configuration file.
2016-01-29T17:01:48.756Z - info: Executing box spinup.
2016-01-29T17:01:48.797Z - info: Starting spinup attempt 0
2016-01-29T17:01:49.370Z - warn: Spinup attempt 0 failed with error: Command failed: The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

2016-01-29T17:01:49.951Z - info: Starting spinup attempt 1
2016-01-29T17:01:50.483Z - warn: Spinup attempt 1 failed with error: Command failed: The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

2016-01-29T17:01:51.067Z - info: Starting spinup attempt 2
2016-01-29T17:01:51.615Z - warn: Spinup attempt 2 failed with error: Command failed: The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

2016-01-29T17:01:52.161Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Failed to spin up virtual machine after 3 attempts. Error was: Command failed: The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

```
at eval (/private/var/folders/pj/15v2ct6x28n9_ql1b1zk9sdr0000gp/T/.org.chromium.Chromium.CHUi1W/kalabox/installer/install-utils.js:359:22)
at ChildProcess.exithandler (child_process.js:665:7)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Process.ChildProcess._handle.onexit (child_process.js:840:5)
```

async call history is ...
 [ { function: 'install16',
    location: '/private/var/folders/pj/15v2ct6x28n9_ql1b1zk9sdr0000gp/T/.org.chromium.Chromium.CHUi1W/kalabox/installer/installer.js:484:33',
    mapping: { description: 'tail' } } ]
2016-01-29T17:09:09.376Z - info: Box initialized.
2016-01-29T17:09:09.377Z - info: Kalabox Version: 1.0-beta7
2016-01-29T17:09:09.377Z - info: Mac OS Version: 10.11.3

2016-01-29T17:09:09.377Z - info: VirtualBox Version: false
2016-01-29T17:09:09.377Z - info: Vagrant Version: false
2016-01-29T17:09:13.196Z - info: VirtualBox not installed or wrong version. Installing.
2016-01-29T17:09:13.197Z - info: User granted permission to install VirtualBox
2016-01-29T17:09:13.207Z - info: File /var/folders/pj/15v2ct6x28n9_ql1b1zk9sdr0000gp/T/virtualbox-macosx-4.3.6.dmg already downloaded.
2016-01-29T17:09:13.208Z - info: Successfully downloaded VirtualBox DMG.
2016-01-29T17:09:15.730Z - info: Successfully mounted VirtualBox DMG.
2016-01-29T17:09:33.195Z - info: VirtualBox installation complete.
2016-01-29T17:09:33.271Z - info: Successfully ejected VirtualBox DMG.
2016-01-29T17:09:33.272Z - info: Vagrant not installed or wrong version. Installing.
2016-01-29T17:09:33.272Z - info: User granted permission to install Vagrant
2016-01-29T17:09:33.278Z - info: File /var/folders/pj/15v2ct6x28n9_ql1b1zk9sdr0000gp/T/vagrant-macosx-1.4.3.dmg already downloaded.
2016-01-29T17:09:33.279Z - info: Successfully downloaded Vagrant DMG.
2016-01-29T17:09:34.669Z - info: Successfully mounted Vagrant DMG.
2016-01-29T17:09:45.374Z - info: Vagrant installation complete.
2016-01-29T17:09:45.438Z - info: Successfully ejected Vagrant DMG.
2016-01-29T17:09:45.444Z - info: Kalabox image already downloaded.
2016-01-29T17:09:45.445Z - info: Box image downloaded.
2016-01-29T17:09:45.447Z - info: Kalastack already downloaded
2016-01-29T17:09:45.447Z - info: Installing Vagrant plugin vagrant-hostsupdater
2016-01-29T17:09:48.909Z - info: Kalastack downloaded
2016-01-29T17:09:48.909Z - info: Installing Vagrant plugin vagrant-hostsupdater
2016-01-29T17:09:56.478Z - info: Wrote configuration file.
2016-01-29T17:09:56.518Z - info: Executing box spinup.
2016-01-29T17:09:56.559Z - info: Starting spinup attempt 0
2016-01-29T17:09:57.246Z - warn: Spinup attempt 0 failed with error: Command failed: The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

2016-01-29T17:09:57.853Z - info: Starting spinup attempt 1
2016-01-29T17:09:58.393Z - warn: Spinup attempt 1 failed with error: Command failed: The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

2016-01-29T17:09:58.988Z - info: Starting spinup attempt 2
2016-01-29T17:09:59.546Z - warn: Spinup attempt 2 failed with error: Command failed: The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

2016-01-29T17:10:00.128Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Failed to spin up virtual machine after 3 attempts. Error was: Command failed: The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

```
at eval (/private/var/folders/pj/15v2ct6x28n9_ql1b1zk9sdr0000gp/T/.org.chromium.Chromium.ahvFgO/kalabox/installer/install-utils.js:359:22)
at ChildProcess.exithandler (child_process.js:665:7)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Process.ChildProcess._handle.onexit (child_process.js:840:5)
```

async call history is ...
 [ { function: 'install16',
    location: '/private/var/folders/pj/15v2ct6x28n9_ql1b1zk9sdr0000gp/T/.org.chromium.Chromium.ahvFgO/kalabox/installer/installer.js:484:33',
    mapping: { description: 'tail' } } ]
2016-01-29T18:25:49.717Z - info: Box initialized.
2016-01-29T18:25:49.718Z - info: Kalabox Version: 1.0-beta7
2016-01-29T18:25:49.719Z - info: Mac OS Version: 10.11.3

2016-01-29T18:25:49.719Z - info: VirtualBox Version: false
2016-01-29T18:25:49.719Z - info: Vagrant Version: Vagrant 1.4.3

2016-01-29T18:26:05.207Z - info: Existing Vagrant installation, version 1.4.3
2016-01-29T18:26:05.207Z - info: VirtualBox not installed or wrong version. Installing.
2016-01-29T18:26:05.208Z - info: User granted permission to install VirtualBox
2016-01-29T18:26:05.217Z - info: File /var/folders/pj/15v2ct6x28n9_ql1b1zk9sdr0000gp/T/virtualbox-macosx-4.3.6.dmg already downloaded.
2016-01-29T18:26:05.218Z - info: Successfully downloaded VirtualBox DMG.
2016-01-29T18:26:07.411Z - info: Successfully mounted VirtualBox DMG.
2016-01-29T18:26:28.654Z - info: VirtualBox installation complete.
2016-01-29T18:26:39.834Z - info: Successfully ejected VirtualBox DMG.
2016-01-29T18:26:39.857Z - info: Kalabox image already downloaded.
2016-01-29T18:26:39.858Z - info: Box image downloaded.
2016-01-29T18:26:39.860Z - info: Kalastack already downloaded
2016-01-29T18:26:39.860Z - info: Installing Vagrant plugin vagrant-hostsupdater
2016-01-29T18:26:41.712Z - info: Kalastack downloaded
2016-01-29T18:26:41.713Z - info: Installing Vagrant plugin vagrant-hostsupdater
2016-01-29T18:26:48.964Z - info: Wrote configuration file.
2016-01-29T18:26:49.020Z - info: Executing box spinup.
2016-01-29T18:26:49.060Z - info: Starting spinup attempt 0
2016-01-29T18:26:49.723Z - warn: Spinup attempt 0 failed with error: Command failed: The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

2016-01-29T18:26:50.304Z - info: Starting spinup attempt 1
2016-01-29T18:26:50.847Z - warn: Spinup attempt 1 failed with error: Command failed: The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

2016-01-29T18:26:51.431Z - info: Starting spinup attempt 2
2016-01-29T18:26:51.957Z - warn: Spinup attempt 2 failed with error: Command failed: The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

2016-01-29T18:26:52.497Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Failed to spin up virtual machine after 3 attempts. Error was: Command failed: The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

```
at eval (/private/var/folders/pj/15v2ct6x28n9_ql1b1zk9sdr0000gp/T/.org.chromium.Chromium.diCdNm/kalabox/installer/install-utils.js:359:22)
at ChildProcess.exithandler (child_process.js:665:7)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Process.ChildProcess._handle.onexit (child_process.js:840:5)
```

async call history is ...
 [ { function: 'install16',
    location: '/private/var/folders/pj/15v2ct6x28n9_ql1b1zk9sdr0000gp/T/.org.chromium.Chromium.diCdNm/kalabox/installer/installer.js:484:33',
    mapping: { description: 'tail' } } ]
2016-02-02T18:30:06.089Z - info: Box initialized.
2016-02-02T18:30:06.090Z - info: Kalabox Version: 1.0-beta7
2016-02-02T18:30:06.090Z - info: Mac OS Version: 10.11.3

2016-02-02T18:30:06.090Z - info: VirtualBox Version: false
2016-02-02T18:30:06.091Z - info: Vagrant Version: Vagrant 1.4.3

2016-02-02T18:30:09.240Z - info: Existing Vagrant installation, version 1.4.3
2016-02-02T18:30:09.241Z - info: VirtualBox not installed or wrong version. Installing.
2016-02-02T18:30:09.241Z - info: User granted permission to install VirtualBox
2016-02-02T18:31:40.353Z - info: Successfully downloaded VirtualBox DMG.
2016-02-02T18:31:53.166Z - info: Successfully mounted VirtualBox DMG.
2016-02-02T18:32:21.506Z - info: VirtualBox installation complete.
2016-02-02T18:32:22.599Z - info: Successfully ejected VirtualBox DMG.
2016-02-02T18:32:22.616Z - info: Kalabox image already downloaded.
2016-02-02T18:32:22.616Z - info: Box image downloaded.
2016-02-02T18:32:22.617Z - info: Kalastack already downloaded
2016-02-02T18:32:22.618Z - info: Installing Vagrant plugin vagrant-hostsupdater
2016-02-02T18:32:26.321Z - info: Kalastack downloaded
2016-02-02T18:32:26.321Z - info: Installing Vagrant plugin vagrant-hostsupdater
2016-02-02T18:32:36.151Z - info: Wrote configuration file.
2016-02-02T18:32:36.227Z - info: Executing box spinup.
2016-02-02T18:32:36.265Z - info: Starting spinup attempt 0
2016-02-02T18:32:36.967Z - warn: Spinup attempt 0 failed with error: Command failed: The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

2016-02-02T18:32:37.558Z - info: Starting spinup attempt 1
2016-02-02T18:32:38.084Z - warn: Spinup attempt 1 failed with error: Command failed: The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

2016-02-02T18:32:38.662Z - info: Starting spinup attempt 2
2016-02-02T18:32:39.214Z - warn: Spinup attempt 2 failed with error: Command failed: The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

2016-02-02T18:32:39.754Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Failed to spin up virtual machine after 3 attempts. Error was: Command failed: The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

```
at eval (/private/var/folders/pj/15v2ct6x28n9_ql1b1zk9sdr0000gp/T/.org.chromium.Chromium.itInqE/kalabox/installer/install-utils.js:359:22)
at ChildProcess.exithandler (child_process.js:665:7)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Process.ChildProcess._handle.onexit (child_process.js:840:5)
```

async call history is ...
 [ { function: 'install16',
    location: '/private/var/folders/pj/15v2ct6x28n9_ql1b1zk9sdr0000gp/T/.org.chromium.Chromium.itInqE/kalabox/installer/installer.js:484:33',
    mapping: { description: 'tail' } } ]
##

**Comment by pirog** [comment]
hey @nbhatia3 kalabox 1 is not currently maintained or supported. 

I would check out the work being done on Kalabox2 over at https://github.com/kalabox/kalabox
