### ISSUE TITLE
Error: Failed to spin up virtual machine after 3 attempts. Error was: Command failed: The following SSH command responded with a non-zero exit status. Vagrant assumes that this means the command failed!

### ISSUE THREAD

**Issue by bacanapps** [kalamuna/kalaboxv1#32]
### Kalabox Log

2014-06-26T13:29:23.358Z - info: Box initialized.
2014-06-26T13:29:23.359Z - info: Kalabox Version: 1.0-beta6
2014-06-26T13:29:23.359Z - info: Mac OS Version: 10.9.3

2014-06-26T13:29:23.360Z - info: VirtualBox Version: false
2014-06-26T13:29:23.360Z - info: Vagrant Version: false
2014-06-26T13:29:29.169Z - info: VirtualBox not installed or wrong version. Installing.
2014-06-26T13:29:29.169Z - info: User granted permission to install VirtualBox
2014-06-26T13:30:24.724Z - info: Successfully downloaded VirtualBox DMG.
2014-06-26T13:30:34.139Z - info: Successfully mounted VirtualBox DMG.
2014-06-26T13:30:48.742Z - info: VirtualBox installation complete.
2014-06-26T13:30:48.830Z - info: Successfully ejected VirtualBox DMG.
2014-06-26T13:30:48.831Z - info: Vagrant not installed or wrong version. Installing.
2014-06-26T13:30:48.831Z - info: User granted permission to install Vagrant
2014-06-26T13:31:01.240Z - info: Successfully downloaded Vagrant DMG.
2014-06-26T13:31:05.068Z - info: Successfully mounted Vagrant DMG.
2014-06-26T13:31:10.979Z - info: Vagrant installation complete.
2014-06-26T13:31:11.052Z - info: Successfully ejected Vagrant DMG.
2014-06-26T13:31:11.058Z - info: Kalabox image already downloaded.
2014-06-26T13:31:11.058Z - info: Box image downloaded.
2014-06-26T13:31:11.982Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-06-26T13:31:13.771Z - info: Kalastack downloaded
2014-06-26T13:31:13.772Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-06-26T13:31:53.012Z - info: Wrote configuration file.
2014-06-26T13:31:53.049Z - info: Executing box spinup.
2014-06-26T13:31:53.087Z - info: Starting spinup attempt 0
2014-06-26T13:33:07.218Z - warn: Spinup attempt 0 failed with error: Command failed: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 1.3.3.1:'/Users/user/kalabox/www' /var/www

Stdout from the command:

Stderr from the command:

stdin: is not a tty
mount.nfs: mount to NFS server '1.3.3.1:/Users/user/kalabox/www' failed: timed out, giving up

2014-06-26T13:33:10.523Z - info: Starting spinup attempt 1
2014-06-26T13:34:30.944Z - warn: Spinup attempt 1 failed with error: Command failed: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 1.3.3.1:'/Users/user/kalabox/www' /var/www

Stdout from the command:

Stderr from the command:

stdin: is not a tty
mount.nfs: mount to NFS server '1.3.3.1:/Users/user/kalabox/www' failed: timed out, giving up

2014-06-26T13:34:34.198Z - info: Starting spinup attempt 2
2014-06-26T13:35:46.948Z - warn: Spinup attempt 2 failed with error: Command failed: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 1.3.3.1:'/Users/user/kalabox/www' /var/www

Stdout from the command:

Stderr from the command:

stdin: is not a tty
mount.nfs: mount to NFS server '1.3.3.1:/Users/user/kalabox/www' failed: timed out, giving up

2014-06-26T13:35:50.330Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Failed to spin up virtual machine after 3 attempts. Error was: Command failed: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 1.3.3.1:'/Users/user/kalabox/www' /var/www

Stdout from the command:

Stderr from the command:

stdin: is not a tty
mount.nfs: mount to NFS server '1.3.3.1:/Users/user/kalabox/www' failed: timed out, giving up

```
at eval (/private/var/folders/ym/ff257c3j6fs84zgcgkqt1hzc0000gn/T/.org.chromium.Chromium.eWydsd/kalabox/installer/install-utils.js:359:22)
at ChildProcess.exithandler (child_process.js:659:7)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Socket.eval (child_process.js:994:11)
at Socket.EventEmitter.emit (events.js:98:17)
at Pipe.eval [as close] (net.js:459:12)
```

async call history is ...
 [ { function: 'install16',
    location: '/private/var/folders/ym/ff257c3j6fs84zgcgkqt1hzc0000gn/T/.org.chromium.Chromium.eWydsd/kalabox/installer/installer.js:480:33',
    mapping: { description: 'tail' } } ]
2014-06-26T13:38:57.848Z - info: Box initialized.
2014-06-26T13:38:57.849Z - info: Kalabox Version: 1.0-beta6
2014-06-26T13:38:57.849Z - info: Mac OS Version: 10.9.3

2014-06-26T13:38:57.849Z - info: VirtualBox Version: 4.3.6r91406

2014-06-26T13:38:57.849Z - info: Vagrant Version: Vagrant 1.4.3

2014-06-26T13:39:15.569Z - info: Existing VirtualBox installation, version 4.3.6
2014-06-26T13:39:15.570Z - info: Existing Vagrant installation, version 1.4.3
2014-06-26T13:39:15.576Z - info: Kalabox image already downloaded.
2014-06-26T13:39:15.577Z - info: Box image downloaded.
2014-06-26T13:39:15.579Z - info: Kalastack already downloaded
2014-06-26T13:39:15.580Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-06-26T13:39:16.544Z - info: Kalastack downloaded
2014-06-26T13:39:16.545Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-06-26T13:39:46.554Z - info: Wrote configuration file.
2014-06-26T13:39:46.588Z - info: Executing box spinup.
2014-06-26T13:39:46.621Z - info: Starting spinup attempt 0
2014-06-26T13:40:57.586Z - warn: Spinup attempt 0 failed with error: Command failed: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 1.3.3.1:'/Users/user/kalabox/www' /var/www

Stdout from the command:

Stderr from the command:

stdin: is not a tty
mount.nfs: mount to NFS server '1.3.3.1:/Users/user/kalabox/www' failed: timed out, giving up

2014-06-26T13:41:00.759Z - info: Starting spinup attempt 1
2014-06-26T13:42:11.575Z - warn: Spinup attempt 1 failed with error: Command failed: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 1.3.3.1:'/Users/user/kalabox/www' /var/www

Stdout from the command:

Stderr from the command:

stdin: is not a tty
mount.nfs: mount to NFS server '1.3.3.1:/Users/user/kalabox/www' failed: timed out, giving up

2014-06-26T13:42:14.729Z - info: Starting spinup attempt 2
2014-06-26T13:43:25.232Z - warn: Spinup attempt 2 failed with error: Command failed: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 1.3.3.1:'/Users/user/kalabox/www' /var/www

Stdout from the command:

Stderr from the command:

stdin: is not a tty
mount.nfs: mount to NFS server '1.3.3.1:/Users/user/kalabox/www' failed: timed out, giving up

2014-06-26T13:43:28.344Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Failed to spin up virtual machine after 3 attempts. Error was: Command failed: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 1.3.3.1:'/Users/user/kalabox/www' /var/www

Stdout from the command:

Stderr from the command:

stdin: is not a tty
mount.nfs: mount to NFS server '1.3.3.1:/Users/user/kalabox/www' failed: timed out, giving up

```
at eval (/private/var/folders/ym/ff257c3j6fs84zgcgkqt1hzc0000gn/T/.org.chromium.Chromium.04hFRP/kalabox/installer/install-utils.js:359:22)
at ChildProcess.exithandler (child_process.js:659:7)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Process.ChildProcess._handle.onexit (child_process.js:840:5)
```

async call history is ...
 [ { function: 'install16',
    location: '/private/var/folders/ym/ff257c3j6fs84zgcgkqt1hzc0000gn/T/.org.chromium.Chromium.04hFRP/kalabox/installer/installer.js:480:33',
    mapping: { description: 'tail' } } ]
2014-06-27T11:24:12.809Z - info: Box initialized.
2014-06-27T11:24:12.810Z - info: Kalabox Version: 1.0-beta6
2014-06-27T11:24:12.811Z - info: Mac OS Version: 10.9.3

2014-06-27T11:24:12.811Z - info: VirtualBox Version: 4.3.6r91406

2014-06-27T11:24:12.811Z - info: Vagrant Version: Vagrant 1.4.3

2014-06-27T11:24:14.697Z - info: Existing VirtualBox installation, version 4.3.6
2014-06-27T11:24:14.698Z - info: Existing Vagrant installation, version 1.4.3
2014-06-27T11:24:14.706Z - info: Kalabox image already downloaded.
2014-06-27T11:24:14.706Z - info: Box image downloaded.
2014-06-27T11:24:14.708Z - info: Kalastack already downloaded
2014-06-27T11:24:14.709Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-06-27T11:24:15.976Z - info: Kalastack downloaded
2014-06-27T11:24:15.977Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-06-27T11:24:29.939Z - info: Wrote configuration file.
2014-06-27T11:24:29.978Z - info: Executing box spinup.
2014-06-27T11:24:30.022Z - info: Starting spinup attempt 0
2014-06-27T11:25:45.282Z - warn: Spinup attempt 0 failed with error: Command failed: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 1.3.3.1:'/Users/user/kalabox/www' /var/www

Stdout from the command:

Stderr from the command:

stdin: is not a tty
mount.nfs: mount to NFS server '1.3.3.1:/Users/user/kalabox/www' failed: timed out, giving up

2014-06-27T11:25:49.513Z - info: Starting spinup attempt 1
2014-06-27T11:27:14.954Z - warn: Spinup attempt 1 failed with error: Command failed: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 1.3.3.1:'/Users/user/kalabox/www' /var/www

Stdout from the command:

Stderr from the command:

stdin: is not a tty
mount.nfs: mount to NFS server '1.3.3.1:/Users/user/kalabox/www' failed: timed out, giving up

2014-06-27T11:27:18.364Z - info: Starting spinup attempt 2
2014-06-27T11:28:31.361Z - warn: Spinup attempt 2 failed with error: Command failed: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 1.3.3.1:'/Users/user/kalabox/www' /var/www

Stdout from the command:

Stderr from the command:

stdin: is not a tty
mount.nfs: mount to NFS server '1.3.3.1:/Users/user/kalabox/www' failed: timed out, giving up

2014-06-27T11:28:35.604Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Failed to spin up virtual machine after 3 attempts. Error was: Command failed: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 1.3.3.1:'/Users/user/kalabox/www' /var/www

Stdout from the command:

Stderr from the command:

stdin: is not a tty
mount.nfs: mount to NFS server '1.3.3.1:/Users/user/kalabox/www' failed: timed out, giving up

```
at eval (/private/var/folders/ym/ff257c3j6fs84zgcgkqt1hzc0000gn/T/.org.chromium.Chromium.lghNkQ/kalabox/installer/install-utils.js:359:22)
at ChildProcess.exithandler (child_process.js:659:7)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Process.ChildProcess._handle.onexit (child_process.js:840:5)
```

async call history is ...
 [ { function: 'install16',
    location: '/private/var/folders/ym/ff257c3j6fs84zgcgkqt1hzc0000gn/T/.org.chromium.Chromium.lghNkQ/kalabox/installer/installer.js:480:33',
    mapping: { description: 'tail' } } ]
##

**Comment by pirog** [comment]
Can you try out the resolution proposed here?
https://github.com/kalamuna/kalastack/issues/92
