### ISSUE TITLE
Undefined error in nue.js workflow during VirtualBox Installation

### ISSUE THREAD

**Issue by reynoldsalec** [kalamuna/kalaboxv1#4]
An error is occuring after the VirtualBox DMG has been installed in the installer.js workflow; see below log. Have several tickets in the Kalabox queue relating to this; haven't been able to replicate.

2014-06-04T18:02:02.698Z - info: Box initialized. 
2014-06-04T18:02:02.698Z - info: Kalabox Version: 1.0-beta5 
2014-06-04T18:02:02.699Z - info: Mac OS Version: 10.9.3

2014-06-04T18:02:02.699Z - info: VirtualBox Version: 4.3.12r93733

2014-06-04T18:02:02.699Z - info: Vagrant Version: Vagrant 1.6.3

2014-06-04T18:02:36.841Z - info: User accepted license. 
2014-06-04T18:02:40.743Z - info: Existing VirtualBox installation, 
version 4.3.12 
2014-06-04T18:02:40.743Z - info: Existing Vagrant installation, version 1.6.3 
2014-06-04T18:02:40.744Z - info: VirtualBox not installed or wrong 
version. Installing. 
2014-06-04T18:02:53.427Z - info: User granted permission to install VirtualBox 
2014-06-05T15:23:52.832Z - info: Box initialized. 
2014-06-05T15:23:52.833Z - info: Kalabox Version: 1.0-beta5 
2014-06-05T15:23:52.833Z - info: Mac OS Version: 10.9.3

2014-06-05T15:23:52.833Z - info: VirtualBox Version: 4.3.12r93733

2014-06-05T15:23:52.833Z - info: Vagrant Version: Vagrant 1.6.3

2014-06-05T15:23:56.880Z - info: User accepted license. 
2014-06-05T15:23:57.537Z - info: Existing VirtualBox installation, 
version 4.3.12 
2014-06-05T15:23:57.537Z - info: Existing Vagrant installation, version 1.6.3 
2014-06-05T15:23:57.538Z - info: VirtualBox not installed or wrong 
version. Installing. 
2014-06-05T15:24:04.468Z - info: User granted permission to install VirtualBox 
2014-06-05T15:25:06.848Z - info: Successfully downloaded VirtualBox DMG. 
2014-06-05T15:25:08.002Z - error: Error during installation routine: 
An error occurred in an async call. 
cause stack is ... 
undefined 
async call history is ... 
[ { function: 'install3', 
location: '/private/var/folders/j7/r9055hy952949pv8tb1b9x1c0000gq/T/.org.chromium.Chromium.kf9vgW/kalabox/installer/installer.js:337:121', 
mapping: { description: 'tail' } } ]

**Comment by reynoldsalec** [comment]
Tried upgrading my VirtualBox to 4.3.12 to see if I could replicate the issue, no dice there on my pre-installed version.

**Comment by pirog** [comment]
@reynoldsalec my guess here is they are running vagrant 1.5+ which i dont think works with kalabox yet. I would see if downgrading to the "supported" release of vagrant (1.4.3) does the trick.

Might want to ping the zendesk people who have this issue and try to direct them here instead.

**Comment by pirog** [comment]
This could also potentially be caused by a corrupt DMG

**Comment by katebron** [comment]
Potentially the same problem:
2014-06-14T14:37:28.944Z - info: Box initialized.
2014-06-14T14:37:28.945Z - info: Kalabox Version: 1.0-beta5
2014-06-14T14:37:28.945Z - info: Mac OS Version: 10.7.5

2014-06-14T14:37:28.945Z - info: VirtualBox Version: false
2014-06-14T14:37:28.945Z - info: Vagrant Version: false
2014-06-14T14:37:40.065Z - info: User accepted license.
2014-06-14T14:39:43.398Z - error: Error during installation routine: An
error occurred in an async call.
cause stack is ...
Error: Command failed: sudo-pass.scpt:273:507: execution error:
SystemUIServer got an error: AppleEvent timed out. (-1712)

at ChildProcess.exithandler (child_process.js:661:12)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Process.ChildProcess._handle.onexit (child_process.js:840:5)
async call history is ...
[ { function: 'getPassword0',
location:
'/private/var/folders/_6/p5h83vwx4c39gnjvgdy2vjlh0000gp/T/.org.chromium.Chromium.YkZRu0/kalabox/utils/task-runner/sudo-runner.js:160:61',
mapping: { description: 'tail' } },
{ function: 'runCommand1',
location:
'/private/var/folders/_6/p5h83vwx4c39gnjvgdy2vjlh0000gp/T/.org.chromium.Chromium.YkZRu0/kalabox/utils/task-runner/sudo-runner.js:49:24',
mapping: { description: 'tail' } },
{ function: 'installGetPassword',
location:
'/private/var/folders/_6/p5h83vwx4c39gnjvgdy2vjlh0000gp/T/.org.chromium.Chromium.YkZRu0/kalabox/installer/installer.js:259:71',
mapping: { description: 'tail' } } ]
2014-06-14T14:56:00.395Z - info: Box initialized.
2014-06-14T14:56:00.396Z - info: Kalabox Version: 1.0-beta5
2014-06-14T14:56:00.397Z - info: Mac OS Version: 10.7.5

2014-06-14T14:56:00.397Z - info: VirtualBox Version: false
2014-06-14T14:56:00.397Z - info: Vagrant Version: false
2014-06-14T14:56:04.412Z - info: User accepted license.
2014-06-14T14:56:13.091Z - info: VirtualBox not installed or wrong version.
Installing.
2014-06-14T14:56:13.091Z - info: User granted permission to install
VirtualBox
2014-06-14T14:58:10.193Z - info: Successfully downloaded VirtualBox DMG.
2014-06-14T14:58:22.377Z - info: Successfully mounted VirtualBox DMG.
2014-06-14T14:58:50.458Z - info: VirtualBox installation complete.
2014-06-14T14:58:50.665Z - info: Successfully ejected VirtualBox DMG.
2014-06-14T14:58:50.665Z - info: Vagrant not installed or wrong version.
Installing.
2014-06-14T14:58:50.666Z - info: User granted permission to install Vagrant
2014-06-14T14:59:21.211Z - info: Successfully downloaded Vagrant DMG.
2014-06-14T14:59:27.121Z - info: Successfully mounted Vagrant DMG.
2014-06-14T14:59:36.034Z - info: Vagrant installation complete.
2014-06-14T14:59:36.119Z - info: Successfully ejected Vagrant DMG.
2014-06-14T15:04:37.124Z - info: Box image downloaded.
2014-06-14T15:04:38.012Z - info: Installing Vagrant plugin
vagrant-hostsupdater
2014-06-14T15:04:41.450Z - info: Kalastack downloaded
2014-06-14T15:04:41.450Z - info: Installing Vagrant plugin
vagrant-hostsupdater
2014-06-14T15:04:59.651Z - error: Error during installation routine: An
error occurred in an async call.
cause stack is ...
Error: Command failed: The plugin 'vagrant-hostsupdater' could not be
found in local or remote
repositories. Please check the name of the plugin and try again.

at ChildProcess.exithandler (child_process.js:661:12)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Socket.eval (child_process.js:994:11)
at Socket.EventEmitter.emit (events.js:98:17)
at Pipe.eval [as close](net.js:459:12)
async call history is ...
[ { function: 'eval',
location:
'/private/var/folders/_6/p5h83vwx4c39gnjvgdy2vjlh0000gp/T/.org.chromium.Chromium.kRo20h/kalabox/installer/installer.js:438:123',
mapping: { description: 'tail' } } ]
2014-06-14T15:10:49.247Z - info: Box initialized.
2014-06-14T15:10:49.248Z - info: Kalabox Version: 1.0-beta5
2014-06-14T15:10:49.248Z - info: Mac OS Version: 10.7.5

2014-06-14T15:10:49.248Z - info: VirtualBox Version: 4.3.6r91406

2014-06-14T15:10:49.248Z - info: Vagrant Version: Vagrant 1.4.3

2014-06-14T15:10:52.337Z - info: User accepted license.
2014-06-14T15:10:52.342Z - info: User accepted license.
2014-06-14T15:10:52.771Z - info: Existing VirtualBox installation, version
4.3.6
2014-06-14T15:10:52.771Z - info: Existing Vagrant installation, version
1.4.3
2014-06-14T15:10:52.782Z - info: Existing VirtualBox installation, version
4.3.6
2014-06-14T15:10:52.782Z - info: Existing Vagrant installation, version
1.4.3
2014-06-14T15:10:52.789Z - info: Kalabox image already downloaded.
2014-06-14T15:10:52.790Z - info: Box image downloaded.
2014-06-14T15:10:52.792Z - info: Kalabox image already downloaded.
2014-06-14T15:10:52.793Z - info: Kalastack already downloaded
2014-06-14T15:10:52.793Z - info: Installing Vagrant plugin
vagrant-hostsupdater
2014-06-14T15:10:52.797Z - info: Box image downloaded.
2014-06-14T15:10:52.799Z - info: Kalastack already downloaded
2014-06-14T15:10:52.799Z - info: Installing Vagrant plugin
vagrant-hostsupdater
2014-06-14T15:10:53.835Z - info: Kalastack downloaded
2014-06-14T15:10:53.835Z - info: Installing Vagrant plugin
vagrant-hostsupdater
2014-06-14T15:10:53.838Z - info: Kalastack downloaded
2014-06-14T15:10:53.839Z - info: Installing Vagrant plugin
vagrant-hostsupdater
2014-06-14T15:11:05.872Z - info: Adding base box image to Vagrant.
2014-06-14T15:11:06.395Z - info: Adding base box image to Vagrant.
2014-06-14T15:11:28.818Z - error: Error during installation routine: An
error occurred in an async call.
cause stack is ...
Error: Command failed:
/Applications/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:1427:in `rmdir':
Directory not empty -
/Users/--username--/.vagrant.d/boxes/kalabox/virtualbox (Errno::ENOTEMPTY)
from /Applications/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:1427:in
`block in remove_dir1'
from /Applications/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:1438:in
`platform_support'
from /Applications/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:1426:in
`remove_dir1'
from /Applications/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:1419:in
`remove'
from /Applications/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:770:in
`block in remove_entry'
from /Applications/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:1475:in
`postorder_traverse'
from /Applications/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:768:in
`remove_entry'
from /Applications/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:626:in
`block in rm_r'
from /Applications/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:622:in
`each'
from /Applications/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:622:in
`rm_r'
from /Applications/Vagrant/embedded/lib/ruby/2.0.0/pathname.rb:567:in
`rmtree'
from
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/box_collection.rb:166:in
`block (3 levels) in add'
from
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/box_collection.rb:388:in
`with_temp_dir'
from
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/box_collection.rb:125:in
`block (2 levels) in add'
from
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/box_collection.rb:388:in
`with_temp_dir'
from
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/box_collection.rb:109:in
`block in add'
from
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/box_collection.rb:375:in
`block in with_collection_lock'
from
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/box_collection.rb:374:in
`synchronize'
from
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/box_collection.rb:374:in
`with_collection_lock'
from
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/box_collection.rb:77:in
`add'
from
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builtin/box_add.rb:112:in
`call'
from
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in
`call'
from
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builder.rb:116:in
`call'
from
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in
`block in run'
from
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/util/busy.rb:19:in
`busy'
from
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in
`run'
from
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/plugins/commands/box/command/add.rb:58:in
`execute'
from
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/plugins/commands/box/command/root.rb:51:in
`execute'
from
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/cli.rb:38:in
`execute'
from
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/environment.rb:484:in
`cli'
from
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/bin/vagrant:127:in
`<top (required)>'
from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in`<main>'

at ChildProcess.exithandler (child_process.js:661:12)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Socket.eval (child_process.js:994:11)
at Socket.EventEmitter.emit (events.js:98:17)
at Pipe.eval [as close](net.js:459:12)
async call history is ...
[ { function: 'install13',
location:
'/private/var/folders/_6/p5h83vwx4c39gnjvgdy2vjlh0000gp/T/.org.chromium.Chromium.2jMq9m/kalabox/installer/installer.js:459:109',
mapping: { description: 'tail' } } ]
2014-06-14T15:11:28.827Z - info: Wrote configuration file.

**Comment by pirog** [comment]
I have also seen a permission denied error for the SSH askpass which might be the issue as well.

One possible thing we could do is to stop forwarding in the users SSH key and just rely on kalabox to handle all of the keys. This would be simpler and more stable.

**Comment by reynoldsalec** [comment]
@katebron looks like you had two separate issues when trying to install. The first time installing the vagrant plugin host-updater failed. Second time that worked, but looks like some material created during the first installation (specifically the $HOME/.vagrant.d/boxes/kalabox directory) got in the way of the second installation. As an immediate step to get Kalabox running, I would delete that directory (rm -r $HOME/.vagrant.d/boxes/kalabox) and try installing again.

@pirog for @katebron's issue, should we add something to the install script to make sure that $HOME/.vagrant.d/boxes/kalabox doesn't exist and delete it if it does?

**Comment by pirog** [comment]
@reynoldsalec yeah i definitely think its good to be as clean as possible for the full uninstall.
