### ISSUE TITLE
Can't install correctly

### ISSUE THREAD

**Issue by tschet** [kalamuna/kalaboxv1#44]
### Kalabox Log

2014-07-05T16:38:57.855Z - info: Box initialized.
2014-07-05T16:38:57.856Z - info: Kalabox Version: 1.0-beta6
2014-07-05T16:38:57.856Z - info: Mac OS Version: 10.9.3

2014-07-05T16:38:57.857Z - info: VirtualBox Version: false
2014-07-05T16:38:57.857Z - info: Vagrant Version: false
2014-07-05T16:39:02.059Z - info: VirtualBox not installed or wrong version. Installing.
2014-07-05T16:39:02.060Z - info: User granted permission to install VirtualBox
2014-07-05T16:43:02.487Z - info: Successfully downloaded VirtualBox DMG.
2014-07-05T16:43:13.206Z - info: Successfully mounted VirtualBox DMG.
2014-07-05T16:43:27.031Z - info: VirtualBox installation complete.
2014-07-05T16:43:27.087Z - info: Successfully ejected VirtualBox DMG.
2014-07-05T16:43:27.087Z - info: Vagrant not installed or wrong version. Installing.
2014-07-05T16:43:27.088Z - info: User granted permission to install Vagrant
2014-07-05T16:44:48.601Z - info: Successfully downloaded Vagrant DMG.
2014-07-05T16:44:53.083Z - info: Successfully mounted Vagrant DMG.
2014-07-05T16:45:01.515Z - info: Vagrant installation complete.
2014-07-05T16:45:01.557Z - info: Successfully ejected Vagrant DMG.
2014-07-05T16:54:34.455Z - info: Box image downloaded.
2014-07-05T16:54:35.879Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-07-05T16:54:37.615Z - info: Kalastack downloaded
2014-07-05T16:54:37.616Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-07-05T16:54:49.949Z - info: Wrote configuration file.
2014-07-05T16:54:49.981Z - info: Executing box spinup.
2014-07-05T16:54:50.013Z - info: Starting spinup attempt 0
2014-07-05T16:54:50.664Z - warn: Spinup attempt 0 failed with error: Command failed: The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

2014-07-05T16:54:51.277Z - info: Starting spinup attempt 1
2014-07-05T16:54:51.837Z - warn: Spinup attempt 1 failed with error: Command failed: The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

2014-07-05T16:54:52.443Z - info: Starting spinup attempt 2
2014-07-05T16:54:53.000Z - warn: Spinup attempt 2 failed with error: Command failed: The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

2014-07-05T16:54:53.572Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Failed to spin up virtual machine after 3 attempts. Error was: Command failed: The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

```
at eval (/private/var/folders/dz/bnnd6kq96w387zpmdh4lwrtc0000gn/T/.org.chromium.Chromium.GWMFQ6/kalabox/installer/install-utils.js:359:22)
at ChildProcess.exithandler (child_process.js:665:7)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Socket.eval (child_process.js:994:11)
at Socket.EventEmitter.emit (events.js:98:17)
at Pipe.eval [as close] (net.js:459:12)
```

async call history is ...
 [ { function: 'install16',
    location: '/private/var/folders/dz/bnnd6kq96w387zpmdh4lwrtc0000gn/T/.org.chromium.Chromium.GWMFQ6/kalabox/installer/installer.js:479:33',
    mapping: { description: 'tail' } } ]

**Comment by tschet** [comment]
I'm using OS X 10.9.3.  I've tried installing multiple times with uninstall run in between. I originally had Virtualbox installed, but I've now tried it with and without Virtualbox installed. The errors always seen to be the same.

**Comment by pirog** [comment]
Have you tried to run "vboxmanage --version" on the command line as the message suggests? What does it tell you?

**Comment by tschet** [comment]
When I use that command, it comes back with 4.3.6r91406.

Douglas Tschetter
701.202.6191
me@douglast.com

**Comment by pirog** [comment]
That is definitely what it is supposed to do so that is weird. 

Before you uninstalled did you originally have vagrant installed as well? Are you doing the complete uninstall which is option #2?

**Comment by tschet** [comment]
I did the complete install (2). I did not have vagrant installed at all.
- Douglas

**Comment by tschet** [comment]
I just ran it one more time and it worked perfectly. Better internet connection here, but otherwise the same. Thanks for the help!
- Douglas

**Comment by pirog** [comment]
Sometimes on poor connections the box downloader can fail but it usually reports that. Glad it worked on teh second try!
