### ISSUE TITLE
Delete site issue and upon reinstall, unable to create site

### ISSUE THREAD

**Issue by possiBri** [kalamuna/kalaboxv1#76]
Hi again,

I tried deleting a site through the GUI, but it continued to show in the sites list. I found that the site folder was still in the www directory, so I deleted it and that removed the site from the list in the GUI. However, I was then unable to spin up a new site — the process would just hang. I thought I might've caused the problem, so I decided to uninstall and reinstall.

I had to do this multiple times, as the install kept hanging. Now that I have it installed, as soon as the servers start up I get this error again:
"There's a problem with loading your sites list. Restarting the box may resolve it."

I have tried restarting the servers through the GUI, quitting and restarting the app, restarting the computer, and even uninstalling and reinstalling the app. I'm going to try uninstall/reinstall once more but here are the results from kala.log in case it doesn't work:
### Kalabox Log

2014-07-15T22:47:30.255Z - info: Box initialized.
2014-07-15T22:47:30.256Z - info: Kalabox Version: 1.0-beta6
2014-07-15T22:47:30.257Z - info: Mac OS Version: 10.9.4

2014-07-15T22:47:30.257Z - info: VirtualBox Version: false
2014-07-15T22:47:30.257Z - info: Vagrant Version: false
2014-07-15T22:47:36.063Z - info: VirtualBox not installed or wrong version. Installing.
2014-07-15T22:47:36.063Z - info: User granted permission to install VirtualBox
2014-07-15T22:48:22.837Z - info: Successfully downloaded VirtualBox DMG.
2014-07-15T22:48:34.171Z - info: Successfully mounted VirtualBox DMG.
2014-07-15T22:48:50.144Z - info: VirtualBox installation complete.
2014-07-15T22:49:00.242Z - info: Successfully ejected VirtualBox DMG.
2014-07-15T22:49:00.243Z - info: Vagrant not installed or wrong version. Installing.
2014-07-15T22:49:00.244Z - info: User granted permission to install Vagrant
2014-07-15T22:49:05.605Z - info: Successfully downloaded Vagrant DMG.
2014-07-15T22:49:09.082Z - info: Successfully mounted Vagrant DMG.
2014-07-15T22:49:14.544Z - info: Vagrant installation complete.
2014-07-15T22:49:24.602Z - info: Successfully ejected Vagrant DMG.
2014-07-15T22:50:10.493Z - info: Box image downloaded.
2014-07-15T22:50:10.678Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-07-15T22:50:11.389Z - info: Kalastack downloaded
2014-07-15T22:50:11.391Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-07-15T22:50:17.914Z - info: Wrote configuration file.
2014-07-15T22:50:17.943Z - info: Executing box spinup.
2014-07-15T22:50:17.977Z - info: Starting spinup attempt 0
2014-07-15T22:51:23.573Z - warn: Spinup attempt 0 failed with error: Command failed: Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.

2014-07-15T22:51:26.826Z - info: Starting spinup attempt 1
2014-07-15T22:58:55.347Z - info: Box initialized.
2014-07-15T22:58:55.348Z - info: Kalabox Version: 1.0-beta6
2014-07-15T22:58:55.348Z - info: Mac OS Version: 10.9.4

2014-07-15T22:58:55.348Z - info: VirtualBox Version: 4.3.6r91406

2014-07-15T22:58:55.348Z - info: Vagrant Version: Vagrant 1.4.3

2014-07-15T22:58:55.349Z - info: Installation completed successfully.
2014-07-15T22:58:55.935Z - info: Existing VirtualBox installation, version 4.3.6
2014-07-15T22:58:55.935Z - info: Existing Vagrant installation, version 1.4.3
2014-07-15T22:58:55.943Z - info: Kalabox image already downloaded.
2014-07-15T22:58:55.943Z - info: Box image downloaded.
2014-07-15T22:58:55.946Z - info: Kalastack already downloaded
2014-07-15T22:58:55.946Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-07-15T22:58:56.363Z - warn: Error retrieving sites list: Error: getaddrinfo ENOTFOUND
2014-07-15T22:58:56.829Z - info: Kalastack downloaded
2014-07-15T22:58:56.830Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-07-15T22:59:03.510Z - info: Wrote configuration file.
2014-07-15T22:59:03.538Z - info: Executing box spinup.
2014-07-15T22:59:03.569Z - info: Starting spinup attempt 0
2014-07-15T22:59:06.285Z - info: Box initialized.
2014-07-15T22:59:06.285Z - info: Kalabox Version: 1.0-beta6
2014-07-15T22:59:06.285Z - info: Mac OS Version: 10.9.4

2014-07-15T22:59:06.285Z - info: VirtualBox Version: 4.3.6r91406

2014-07-15T22:59:06.286Z - info: Vagrant Version: Vagrant 1.4.3

2014-07-15T22:59:06.286Z - info: Installation completed successfully.
2014-07-15T22:59:26.209Z - warn: Error retrieving sites list: Error: getaddrinfo ENOTFOUND
2014-07-15T22:59:37.045Z - warn: Command failed: The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'poweroff' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

2014-07-15T23:05:26.661Z - info: Box initialized.
2014-07-15T23:05:26.663Z - info: Kalabox Version: 1.0-beta6
2014-07-15T23:05:26.663Z - info: Mac OS Version: 10.9.4

2014-07-15T23:05:26.663Z - info: VirtualBox Version: 4.3.6r91406

2014-07-15T23:05:26.663Z - info: Vagrant Version: Vagrant 1.4.3

2014-07-15T23:06:14.088Z - warn: Updates check failed: An error occurred in an async call.
cause stack is ...
  Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:41:10)
    at Object.onlookup [as oncomplete](dns.js:91:26)
async call history is ...
 [ { function: 'checkForUpdates0',
    location: '/private/var/folders/3l/l9kx27m14ggc37krp_q7dh2h0000gp/T/.org.chromium.Chromium.MLxt0K/kalabox/updater.js:47:30',
    mapping: { index: 2 } } ]
2014-07-15T23:06:14.604Z - warn: Error retrieving sites list: SyntaxError: Unexpected token <
2014-07-15T23:20:02.593Z - warn: Command failed: A VirtualBox machine with the name 'kala.49ef09c97bd8c5d8cbc25a2f9cd8ab11.box' already exists.
Please use another name or delete the machine with the existing
name, and try again.

2014-07-15T23:20:02.602Z - warn: Command failed: A VirtualBox machine with the name 'kala.49ef09c97bd8c5d8cbc25a2f9cd8ab11.box' already exists.
Please use another name or delete the machine with the existing
name, and try again.

2014-07-16T01:31:23.031Z - info: Box initialized.
2014-07-16T01:31:23.033Z - info: Kalabox Version: 1.0-beta6
2014-07-16T01:31:23.034Z - info: Mac OS Version: 10.9.4

2014-07-16T01:31:23.034Z - info: VirtualBox Version: 4.3.6r91406

2014-07-16T01:31:23.034Z - info: Vagrant Version: Vagrant 1.4.3

2014-07-16T01:36:18.247Z - info: Box initialized.
2014-07-16T01:36:18.248Z - info: Kalabox Version: 1.0-beta6
2014-07-16T01:36:18.248Z - info: Mac OS Version: 10.9.4

2014-07-16T01:36:18.248Z - info: VirtualBox Version: 4.3.6r91406

2014-07-16T01:36:18.248Z - info: Vagrant Version: Vagrant 1.4.3

2014-07-16T01:37:05.410Z - warn: Error retrieving sites list: SyntaxError: Unexpected token <
2014-07-17T05:00:13.155Z - info: Box initialized.
2014-07-17T05:00:13.157Z - info: Kalabox Version: 1.0-beta6
2014-07-17T05:00:13.157Z - info: Mac OS Version: 10.9.4

2014-07-17T05:00:13.157Z - info: VirtualBox Version: 4.3.6r91406

2014-07-17T05:00:13.157Z - info: Vagrant Version: Vagrant 1.4.3

2014-07-17T05:01:01.912Z - info: Box initialized.
2014-07-17T05:01:01.914Z - info: Kalabox Version: 1.0-beta6
2014-07-17T05:01:01.915Z - info: Mac OS Version: 10.9.4

2014-07-17T05:01:01.915Z - info: VirtualBox Version: 4.3.6r91406

2014-07-17T05:01:01.915Z - info: Vagrant Version: Vagrant 1.4.3

2014-07-17T05:02:39.339Z - info: Box initialized.
2014-07-17T05:02:39.340Z - info: Kalabox Version: 1.0-beta6
2014-07-17T05:02:39.340Z - info: Mac OS Version: 10.9.4

2014-07-17T05:02:39.340Z - info: VirtualBox Version: 4.3.6r91406

2014-07-17T05:02:39.340Z - info: Vagrant Version: Vagrant 1.4.3

2014-07-17T05:02:40.701Z - warn: Error retrieving sites list: SyntaxError: Unexpected token <
2014-07-17T05:24:08.946Z - info: Box initialized.
2014-07-17T05:24:08.948Z - info: Kalabox Version: 1.0-beta6
2014-07-17T05:24:08.948Z - info: Mac OS Version: 10.9.4

2014-07-17T05:24:08.948Z - info: VirtualBox Version: 4.3.6r91406

2014-07-17T05:24:08.948Z - info: Vagrant Version: Vagrant 1.4.3

2014-07-17T05:27:20.448Z - info: Box initialized.
2014-07-17T05:27:20.449Z - info: Kalabox Version: 1.0-beta6
2014-07-17T05:27:20.450Z - info: Mac OS Version: 10.9.4

2014-07-17T05:27:20.450Z - info: VirtualBox Version: 4.3.6r91406

2014-07-17T05:27:20.450Z - info: Vagrant Version: Vagrant 1.4.3

2014-07-17T05:27:21.838Z - warn: Error retrieving sites list: SyntaxError: Unexpected token <
2014-07-17T05:31:01.393Z - info: Box initialized.
2014-07-17T05:31:01.394Z - info: Kalabox Version: 1.0-beta6
2014-07-17T05:31:01.394Z - info: Mac OS Version: 10.9.4

2014-07-17T05:31:01.394Z - info: VirtualBox Version: 4.3.6r91406

2014-07-17T05:31:01.394Z - info: Vagrant Version: Vagrant 1.4.3

2014-07-17T05:31:02.709Z - warn: Error retrieving sites list: SyntaxError: Unexpected token <

Thanks!

**Comment by possiBri** [comment]
**Update:** Still getting the same error about not being able to load the sites list when starting up the servers. Also, just a reminder, it says beta6 but it was the beta7 .dmg that I originally downloaded.

Here is my fresh kala.log:

### Kalabox Log

2014-07-17T05:51:16.686Z - info: Box initialized.
2014-07-17T05:51:16.688Z - info: Kalabox Version: 1.0-beta6
2014-07-17T05:51:16.689Z - info: Mac OS Version: 10.9.4

2014-07-17T05:51:16.689Z - info: VirtualBox Version: false
2014-07-17T05:51:16.689Z - info: Vagrant Version: false
2014-07-17T05:51:23.709Z - info: VirtualBox not installed or wrong version. Installing.
2014-07-17T05:51:23.710Z - info: User granted permission to install VirtualBox
2014-07-17T05:58:43.486Z - info: Successfully downloaded VirtualBox DMG.
2014-07-17T05:58:59.180Z - info: Successfully mounted VirtualBox DMG.
2014-07-17T05:59:19.096Z - info: VirtualBox installation complete.
2014-07-17T05:59:29.259Z - info: Successfully ejected VirtualBox DMG.
2014-07-17T05:59:29.259Z - info: Vagrant not installed or wrong version. Installing.
2014-07-17T05:59:29.260Z - info: User granted permission to install Vagrant
2014-07-17T06:00:26.354Z - info: Successfully downloaded Vagrant DMG.
2014-07-17T06:00:30.090Z - info: Successfully mounted Vagrant DMG.
2014-07-17T06:00:38.170Z - info: Vagrant installation complete.
2014-07-17T06:00:48.326Z - info: Successfully ejected Vagrant DMG.
2014-07-17T06:21:38.460Z - info: Box image downloaded.
2014-07-17T06:21:39.389Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-07-17T06:21:41.077Z - info: Kalastack downloaded
2014-07-17T06:21:41.078Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-07-17T06:21:57.756Z - info: Wrote configuration file.
2014-07-17T06:21:57.813Z - info: Executing box spinup.
2014-07-17T06:21:57.871Z - info: Starting spinup attempt 0
2014-07-17T06:35:25.436Z - info: Box initialized.
2014-07-17T06:35:25.437Z - info: Kalabox Version: 1.0-beta6
2014-07-17T06:35:25.437Z - info: Mac OS Version: 10.9.4

2014-07-17T06:35:25.437Z - info: VirtualBox Version: 4.3.6r91406

2014-07-17T06:35:25.437Z - info: Vagrant Version: Vagrant 1.4.3

2014-07-17T06:35:25.438Z - info: Installation completed successfully.
2014-07-17T06:35:26.912Z - info: Existing VirtualBox installation, version 4.3.6
2014-07-17T06:35:26.913Z - info: Existing Vagrant installation, version 1.4.3
2014-07-17T06:35:26.922Z - info: Kalabox image already downloaded.
2014-07-17T06:35:26.923Z - info: Box image downloaded.
2014-07-17T06:35:26.924Z - info: Kalastack already downloaded
2014-07-17T06:35:26.925Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-07-17T06:35:28.333Z - info: Kalastack downloaded
2014-07-17T06:35:28.334Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-07-17T06:35:45.920Z - info: Wrote configuration file.
2014-07-17T06:35:45.971Z - info: Executing box spinup.
2014-07-17T06:35:46.024Z - info: Starting spinup attempt 0
2014-07-17T06:36:02.990Z - info: Box initialized.
2014-07-17T06:36:02.991Z - info: Kalabox Version: 1.0-beta6
2014-07-17T06:36:02.991Z - info: Mac OS Version: 10.9.4

2014-07-17T06:36:02.991Z - info: VirtualBox Version: 4.3.6r91406

2014-07-17T06:36:02.991Z - info: Vagrant Version: Vagrant 1.4.3

2014-07-17T06:36:02.992Z - info: Installation completed successfully.
2014-07-17T14:25:00.056Z - warn: Error retrieving sites list: Error: getaddrinfo ENOTFOUND

**Comment by pirog** [comment]
I've noticed this happening with a few other people and sometimes if you are on a slower machine it seems like the box will try to grab your sites list before it is actually 100% started. In this case i just had to wait like 30 seconds until the box was all the way on and then it would grab my list. 

A good way to verify this is to type in "aliases.kala" in your browser. When this appears in the browser you should be able to see your lists and when it doesnt you may get the error you describe. 

@reynoldsalec may be worth just wrapping this message in some sort of conditional to check?

**Comment by possiBri** [comment]
Hmmm I wouldn't have guessed my machine was particularly slow, since it is a brand new MBP with 2.4gz i5 proc and 16gb RAM. But, I tried waiting a minute or so and **was** able to create a new site, so I guess that was the problem.

As far as the uninstalling of a site, what is the proper method? Should uninstalling the site remove it from the site list AND delete the folder in /www? Thanks!

**Comment by pirog** [comment]
Sorry, slower meaning maybe you have mem locked up doing other stuff not the raw chops of your machine ;)

Right now "removing" a site should just delete the DB, vhost and all of that from the box, and remove the site from the list of downloaded sites. The code usually stays in www but we can remove that too if you think that would be helpful.

**Comment by possiBri** [comment]
Ah, gotcha!

I actually think it's good that it doesn't delete the code (for safety's sake), but when I deleted a site it didn't remove the site from the list in the GUI. I've finally got everything up and running, so I'm not going to mess with it for now, but just an FYI. =]

**Comment by pirog** [comment]
That was our thinking too. 

I know that sometimes there are strange permissions errors that prevent a site from being deleted completed. A good way to debug this is to SSH into the box and run 

drush crush SITENAME.dev --debug --verbose and see where it gets hung up.

**Comment by possiBri** [comment]
Ok great, I will definitely try that if it happens again! Thanks for all your help =]

**Comment by pirog** [comment]
Sure thing! let us know how else we can help!

On Fri, Jul 18, 2014 at 11:42 AM, possiBri notifications@github.com wrote:

> Ok great, I will definitely try that if it happens again! Thanks for all
> your help =]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/76#issuecomment-49465614.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com
