### ISSUE TITLE
Change Password Timeout Length

### ISSUE THREAD

**Issue by ModulesUnraveled** [kalamuna/kalaboxv1#80]
Hey, I just re-installed Mavericks on my MacBook Air. When I installed Kalabox beta 7, I got this error, and it said to post it here... so I am.
### Kalabox Log

2014-07-19T18:52:16.873Z - info: Box initialized.
2014-07-19T18:52:16.874Z - info: Kalabox Version: 1.0-beta6
2014-07-19T18:52:16.874Z - info: Mac OS Version: 10.9.4

2014-07-19T18:52:16.875Z - info: VirtualBox Version: false
2014-07-19T18:52:16.875Z - info: Vagrant Version: false
2014-07-19T18:54:58.106Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Command failed: sudo-pass.scpt:273:507: execution error: SystemUIServer got an error: AppleEvent timed out. (-1712)

```
at ChildProcess.exithandler (child_process.js:661:12)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Socket.eval (child_process.js:994:11)
at Socket.EventEmitter.emit (events.js:98:17)
at Pipe.eval [as close] (net.js:459:12)
```

async call history is ...
 [ { function: 'getPassword0',
    location: '/private/var/folders/v2/l95js92d4v99r5gqp4nc3kc00000gn/T/.org.chromium.Chromium.x7jqP7/kalabox/utils/task-runner/sudo-runner.js:160:61',
    mapping: { description: 'tail' } },
  { function: 'runCommand1',
    location: '/private/var/folders/v2/l95js92d4v99r5gqp4nc3kc00000gn/T/.org.chromium.Chromium.x7jqP7/kalabox/utils/task-runner/sudo-runner.js:49:24',
    mapping: { description: 'tail' } },
  { function: 'installGetPassword',
    location: '/private/var/folders/v2/l95js92d4v99r5gqp4nc3kc00000gn/T/.org.chromium.Chromium.x7jqP7/kalabox/installer/installer.js:258:71',
    mapping: { description: 'tail' } } ]

**Comment by ModulesUnraveled** [comment]
Just tried again and it worked fine. Looks like I didn't enter my password in time.

**Comment by pirog** [comment]
Sounds good!

@reynoldsalec may want to fix this so it doesnt time out or at least doesn't produce an error when it does?

**Comment by reynoldsalec** [comment]
@pirog, good call, changed title of issue to reflect that.

**Comment by pirog** [comment]
still some weird UX funk in edge cases but this should be better and not error out anymore
